#ifndef primary_WATCHDOG_H
#define primary_WATCHDOG_H

#ifdef __cplusplus
extern "C" {
#endif

#define primary_INTERVAL_STEER_VERSION 1000
#define primary_INTERVAL_DAS_VERSION 1000
#define primary_INTERVAL_HV_VERSION 1000
#define primary_INTERVAL_LV_VERSION 1000
#define primary_INTERVAL_TLM_VERSION 1000
#define primary_INTERVAL_TIMESTAMP 1000
#define primary_INTERVAL_AMBIENT_TEMPERATURE 1000
#define primary_INTERVAL_DATA_LOGGER 1000
#define primary_INTERVAL_TLM_STATUS 1000
#define primary_INTERVAL_STEER_SYSTEM_STATUS 1000
#define primary_INTERVAL_HV_VOLTAGE 10
#define primary_INTERVAL_HV_CURRENT 10
#define primary_INTERVAL_HV_TEMP 100
#define primary_INTERVAL_HV_ERRORS 10
#define primary_INTERVAL_TS_STATUS 10
#define primary_INTERVAL_SET_TS_STATUS_HANDCART 100
#define primary_INTERVAL_STEER_STATUS 100
#define primary_INTERVAL_CAR_STATUS 100
#define primary_INTERVAL_DAS_ERRORS 10
#define primary_INTERVAL_LV_CURRENT 500
#define primary_INTERVAL_LV_VOLTAGE 100
#define primary_INTERVAL_LV_TOTAL_VOLTAGE 100
#define primary_INTERVAL_LV_TEMPERATURE 100
#define primary_INTERVAL_COOLING_STATUS 1000
#define primary_INTERVAL_SET_INVERTER_CONNECTION_STATUS 100
#define primary_INTERVAL_INVERTER_CONNECTION_STATUS 100
#define primary_INTERVAL_LV_ERRORS 10
#define primary_INTERVAL_SHUTDOWN_STATUS 500
#define primary_INTERVAL_HV_CELLS_VOLTAGE 100
#define primary_INTERVAL_HV_CELLS_TEMP 100
#define primary_INTERVAL_HV_CELL_BALANCING_STATUS 500
#define primary_INTERVAL_HANDCART_STATUS 500
#define primary_INTERVAL_SPEED 10
#define primary_INTERVAL_INV_L_REQUEST 10
#define primary_INTERVAL_INV_R_REQUEST 10
#define primary_INTERVAL_INV_L_RESPONSE 100
#define primary_INTERVAL_INV_R_RESPONSE 100
#define primary_INTERVAL_CONTROL_OUTPUT 100



#ifdef __cplusplus
}
#endif

#endif // primary_NETWORK_H
