/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Wed Aug  7 12:58:06 2024.
 */

#include <string.h>

#include "simulator_network.h"

static uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int simulator_imu_angular_rate_pack(
    uint8_t *dst_p,
    const simulator_imu_angular_rate_t *src_p,
    size_t byte_size)
{
    uint16_t x;
    uint16_t y;
    uint16_t z;

    if (byte_size < 6u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, 6);

    x = (uint16_t)src_p->x;
    dst_p[0] |= pack_right_shift_u16(x, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(x, 0u, 0xffu);
    y = (uint16_t)src_p->y;
    dst_p[2] |= pack_right_shift_u16(y, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(y, 0u, 0xffu);
    z = (uint16_t)src_p->z;
    dst_p[4] |= pack_right_shift_u16(z, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(z, 0u, 0xffu);

    return (6);
}

int simulator_imu_angular_rate_unpack(
    simulator_imu_angular_rate_t *dst_p,
    const uint8_t *src_p,
    size_t byte_size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    uint16_t x;
    uint16_t y;
    uint16_t z;

    if (byte_size < 6u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    x =  unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    x |=  unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->x = (int16_t)x;
    y =  unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    y |=  unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->y = (int16_t)y;
    z =  unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    z |=  unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->z = (int16_t)z;

    return (0);
}

int16_t simulator_imu_angular_rate_x_encode(float value)
{
    return (int16_t)(canlib_max(-32768, canlib_min(32767, value / 0.1f)));
}

float simulator_imu_angular_rate_x_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool simulator_imu_angular_rate_x_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 2450));
}

int16_t simulator_imu_angular_rate_y_encode(float value)
{
    return (int16_t)(canlib_max(-32768, canlib_min(32767, value / 0.1f)));
}

float simulator_imu_angular_rate_y_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool simulator_imu_angular_rate_y_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 2450));
}

int16_t simulator_imu_angular_rate_z_encode(float value)
{
    return (int16_t)(canlib_max(-32768, canlib_min(32767, value / 0.1f)));
}

float simulator_imu_angular_rate_z_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool simulator_imu_angular_rate_z_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 2450));
}


void simulator_imu_angular_rate_raw_to_conversion(
    simulator_imu_angular_rate_converted_t *conversion,
    float x,
    float y,
    float z
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->x = simulator_imu_angular_rate_x_decode(x);
    conversion->y = simulator_imu_angular_rate_y_decode(y);
    conversion->z = simulator_imu_angular_rate_z_decode(z);
}


void simulator_imu_angular_rate_conversion_to_raw(
    simulator_imu_angular_rate_t *raw,
    float x,
    float y,
    float z
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->x = simulator_imu_angular_rate_x_encode(x);
    raw->y = simulator_imu_angular_rate_y_encode(y);
    raw->z = simulator_imu_angular_rate_z_encode(z);
}


void simulator_imu_angular_rate_raw_to_conversion_struct(
    simulator_imu_angular_rate_converted_t *conversion, 
    const simulator_imu_angular_rate_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->x = simulator_imu_angular_rate_x_decode(raw->x);
    conversion->y = simulator_imu_angular_rate_y_decode(raw->y);
    conversion->z = simulator_imu_angular_rate_z_decode(raw->z);
}


void simulator_imu_angular_rate_conversion_to_raw_struct(
    simulator_imu_angular_rate_t *raw,
    const simulator_imu_angular_rate_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->x = simulator_imu_angular_rate_x_encode(conversion->x);
    raw->y = simulator_imu_angular_rate_y_encode(conversion->y);
    raw->z = simulator_imu_angular_rate_z_encode(conversion->z);
}

int simulator_imu_angular_rate_converted_to_string(simulator_imu_angular_rate_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->x,
    message->y,
    message->z
);
}

int simulator_imu_angular_rate_converted_to_string_file(simulator_imu_angular_rate_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->x,
    message->y,
    message->z
);
}

int simulator_imu_angular_rate_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "x"","
    "y"","
    "z");
}

int simulator_imu_angular_rate_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "x"","
    "y"","
    "z");
}


int simulator_imu_acceleration_pack(
    uint8_t *dst_p,
    const simulator_imu_acceleration_t *src_p,
    size_t byte_size)
{
    uint16_t imu_temperature;
    uint16_t x;
    uint16_t y;
    uint16_t z;

    if (byte_size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, 8);

    x = (uint16_t)src_p->x;
    dst_p[0] |= pack_right_shift_u16(x, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(x, 0u, 0xffu);
    y = (uint16_t)src_p->y;
    dst_p[2] |= pack_right_shift_u16(y, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(y, 0u, 0xffu);
    z = (uint16_t)src_p->z;
    dst_p[4] |= pack_right_shift_u16(z, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(z, 0u, 0xffu);
    imu_temperature = (uint16_t)src_p->imu_temperature;
    dst_p[6] |= pack_right_shift_u16(imu_temperature, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(imu_temperature, 0u, 0xffu);

    return (8);
}

int simulator_imu_acceleration_unpack(
    simulator_imu_acceleration_t *dst_p,
    const uint8_t *src_p,
    size_t byte_size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    uint16_t imu_temperature;
    uint16_t x;
    uint16_t y;
    uint16_t z;

    if (byte_size < 8u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    x =  unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    x |=  unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->x = (int16_t)x;
    y =  unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    y |=  unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->y = (int16_t)y;
    z =  unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    z |=  unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->z = (int16_t)z;
    imu_temperature =  unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    imu_temperature |=  unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->imu_temperature = (int16_t)imu_temperature;

    return (0);
}

int16_t simulator_imu_acceleration_x_encode(float value)
{
    return (int16_t)(canlib_max(-32768, canlib_min(32767, value / 0.01f)));
}

float simulator_imu_acceleration_x_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool simulator_imu_acceleration_x_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 800));
}

int16_t simulator_imu_acceleration_y_encode(float value)
{
    return (int16_t)(canlib_max(-32768, canlib_min(32767, value / 0.01f)));
}

float simulator_imu_acceleration_y_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool simulator_imu_acceleration_y_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 800));
}

int16_t simulator_imu_acceleration_z_encode(float value)
{
    return (int16_t)(canlib_max(-32768, canlib_min(32767, value / 0.01f)));
}

float simulator_imu_acceleration_z_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool simulator_imu_acceleration_z_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 800));
}

bool simulator_imu_acceleration_imu_temperature_is_in_range(int16_t value)
{
    return (value >= 0);
}


void simulator_imu_acceleration_raw_to_conversion(
    simulator_imu_acceleration_converted_t *conversion,
    float x,
    float y,
    float z,
    int16_t imu_temperature
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->x = simulator_imu_acceleration_x_decode(x);
    conversion->y = simulator_imu_acceleration_y_decode(y);
    conversion->z = simulator_imu_acceleration_z_decode(z);
    conversion->imu_temperature = imu_temperature;
}


void simulator_imu_acceleration_conversion_to_raw(
    simulator_imu_acceleration_t *raw,
    float x,
    float y,
    float z,
    int16_t imu_temperature
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->x = simulator_imu_acceleration_x_encode(x);
    raw->y = simulator_imu_acceleration_y_encode(y);
    raw->z = simulator_imu_acceleration_z_encode(z);
    raw->imu_temperature = imu_temperature;
}


void simulator_imu_acceleration_raw_to_conversion_struct(
    simulator_imu_acceleration_converted_t *conversion, 
    const simulator_imu_acceleration_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->x = simulator_imu_acceleration_x_decode(raw->x);
    conversion->y = simulator_imu_acceleration_y_decode(raw->y);
    conversion->z = simulator_imu_acceleration_z_decode(raw->z);
    conversion->imu_temperature = raw->imu_temperature;
}


void simulator_imu_acceleration_conversion_to_raw_struct(
    simulator_imu_acceleration_t *raw,
    const simulator_imu_acceleration_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->x = simulator_imu_acceleration_x_encode(conversion->x);
    raw->y = simulator_imu_acceleration_y_encode(conversion->y);
    raw->z = simulator_imu_acceleration_z_encode(conversion->z);
    raw->imu_temperature = conversion->imu_temperature;
}

int simulator_imu_acceleration_converted_to_string(simulator_imu_acceleration_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f"","
    "%" PRIi16 "",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->x,
    message->y,
    message->z,
    message->imu_temperature
);
}

int simulator_imu_acceleration_converted_to_string_file(simulator_imu_acceleration_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f"","
    "%" PRIi16 "",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->x,
    message->y,
    message->z,
    message->imu_temperature
);
}

int simulator_imu_acceleration_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "x"","
    "y"","
    "z"","
    "imu_temperature");
}

int simulator_imu_acceleration_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "x"","
    "y"","
    "z"","
    "imu_temperature");
}


int simulator_pedal_throttle_pack(
    uint8_t *dst_p,
    const simulator_pedal_throttle_t *src_p,
    size_t byte_size)
{
    if (byte_size < 2u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->throttle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->throttle, 8u, 0xffu);

    return (2);
}

int simulator_pedal_throttle_unpack(
    simulator_pedal_throttle_t *dst_p,
    const uint8_t *src_p,
    size_t byte_size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (byte_size < 2u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->throttle =  unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->throttle =  (dst_p->throttle | unpack_left_shift_u16(src_p[1], 8u, 0xffu));

    return (0);
}

uint16_t simulator_pedal_throttle_throttle_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, value / 1.5259021896696422e-05f)));
}

float simulator_pedal_throttle_throttle_decode(uint16_t value)
{
    return ((float)value * 1.5259021896696422e-05f);
}

bool simulator_pedal_throttle_throttle_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}


void simulator_pedal_throttle_raw_to_conversion(
    simulator_pedal_throttle_converted_t *conversion,
    float throttle
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->throttle = simulator_pedal_throttle_throttle_decode(throttle);
}


void simulator_pedal_throttle_conversion_to_raw(
    simulator_pedal_throttle_t *raw,
    float throttle
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->throttle = simulator_pedal_throttle_throttle_encode(throttle);
}


void simulator_pedal_throttle_raw_to_conversion_struct(
    simulator_pedal_throttle_converted_t *conversion, 
    const simulator_pedal_throttle_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->throttle = simulator_pedal_throttle_throttle_decode(raw->throttle);
}


void simulator_pedal_throttle_conversion_to_raw_struct(
    simulator_pedal_throttle_t *raw,
    const simulator_pedal_throttle_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->throttle = simulator_pedal_throttle_throttle_encode(conversion->throttle);
}

int simulator_pedal_throttle_converted_to_string(simulator_pedal_throttle_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->throttle
);
}

int simulator_pedal_throttle_converted_to_string_file(simulator_pedal_throttle_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->throttle
);
}

int simulator_pedal_throttle_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "throttle");
}

int simulator_pedal_throttle_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "throttle");
}


int simulator_pedal_brakes_pressure_pack(
    uint8_t *dst_p,
    const simulator_pedal_brakes_pressure_t *src_p,
    size_t byte_size)
{
    if (byte_size < 4u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->front, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->front, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->rear, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->rear, 8u, 0xffu);

    return (4);
}

int simulator_pedal_brakes_pressure_unpack(
    simulator_pedal_brakes_pressure_t *dst_p,
    const uint8_t *src_p,
    size_t byte_size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (byte_size < 4u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->front =  unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->front =  (dst_p->front | unpack_left_shift_u16(src_p[1], 8u, 0xffu));
    dst_p->rear =  unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->rear =  (dst_p->rear | unpack_left_shift_u16(src_p[3], 8u, 0xffu));

    return (0);
}

uint16_t simulator_pedal_brakes_pressure_front_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, value / 0.0015259021896696422f)));
}

float simulator_pedal_brakes_pressure_front_decode(uint16_t value)
{
    return ((float)value * 0.0015259021896696422f);
}

bool simulator_pedal_brakes_pressure_front_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t simulator_pedal_brakes_pressure_rear_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, value / 0.0015259021896696422f)));
}

float simulator_pedal_brakes_pressure_rear_decode(uint16_t value)
{
    return ((float)value * 0.0015259021896696422f);
}

bool simulator_pedal_brakes_pressure_rear_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}


void simulator_pedal_brakes_pressure_raw_to_conversion(
    simulator_pedal_brakes_pressure_converted_t *conversion,
    float front,
    float rear
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->front = simulator_pedal_brakes_pressure_front_decode(front);
    conversion->rear = simulator_pedal_brakes_pressure_rear_decode(rear);
}


void simulator_pedal_brakes_pressure_conversion_to_raw(
    simulator_pedal_brakes_pressure_t *raw,
    float front,
    float rear
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->front = simulator_pedal_brakes_pressure_front_encode(front);
    raw->rear = simulator_pedal_brakes_pressure_rear_encode(rear);
}


void simulator_pedal_brakes_pressure_raw_to_conversion_struct(
    simulator_pedal_brakes_pressure_converted_t *conversion, 
    const simulator_pedal_brakes_pressure_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->front = simulator_pedal_brakes_pressure_front_decode(raw->front);
    conversion->rear = simulator_pedal_brakes_pressure_rear_decode(raw->rear);
}


void simulator_pedal_brakes_pressure_conversion_to_raw_struct(
    simulator_pedal_brakes_pressure_t *raw,
    const simulator_pedal_brakes_pressure_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->front = simulator_pedal_brakes_pressure_front_encode(conversion->front);
    raw->rear = simulator_pedal_brakes_pressure_rear_encode(conversion->rear);
}

int simulator_pedal_brakes_pressure_converted_to_string(simulator_pedal_brakes_pressure_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->front,
    message->rear
);
}

int simulator_pedal_brakes_pressure_converted_to_string_file(simulator_pedal_brakes_pressure_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->front,
    message->rear
);
}

int simulator_pedal_brakes_pressure_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "front"","
    "rear");
}

int simulator_pedal_brakes_pressure_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "front"","
    "rear");
}


int simulator_steer_angle_pack(
    uint8_t *dst_p,
    const simulator_steer_angle_t *src_p,
    size_t byte_size)
{
    if (byte_size < 4u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, 4);

    dst_p[0] |= pack_left_shift_u32(src_p->angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->angle, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->angle, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->angle, 24u, 0xffu);

    return (4);
}

int simulator_steer_angle_unpack(
    simulator_steer_angle_t *dst_p,
    const uint8_t *src_p,
    size_t byte_size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (byte_size < 4u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->angle =  unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->angle =  (dst_p->angle | unpack_left_shift_u32(src_p[1], 8u, 0xffu));
    dst_p->angle =  (dst_p->angle | unpack_left_shift_u32(src_p[2], 16u, 0xffu));
    dst_p->angle =  (dst_p->angle | unpack_left_shift_u32(src_p[3], 24u, 0xffu));

    return (0);
}

uint32_t simulator_steer_angle_angle_encode(float value)
{
    return (uint32_t)(canlib_max(0, canlib_min(4294967295, (value - -180.0f) / 8.38190317349087e-08f)));
}

float simulator_steer_angle_angle_decode(uint32_t value)
{
    return (((float)value * 8.38190317349087e-08f) + -180.0f);
}

bool simulator_steer_angle_angle_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}


void simulator_steer_angle_raw_to_conversion(
    simulator_steer_angle_converted_t *conversion,
    float angle
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->angle = simulator_steer_angle_angle_decode(angle);
}


void simulator_steer_angle_conversion_to_raw(
    simulator_steer_angle_t *raw,
    float angle
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->angle = simulator_steer_angle_angle_encode(angle);
}


void simulator_steer_angle_raw_to_conversion_struct(
    simulator_steer_angle_converted_t *conversion, 
    const simulator_steer_angle_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->angle = simulator_steer_angle_angle_decode(raw->angle);
}


void simulator_steer_angle_conversion_to_raw_struct(
    simulator_steer_angle_t *raw,
    const simulator_steer_angle_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->angle = simulator_steer_angle_angle_encode(conversion->angle);
}

int simulator_steer_angle_converted_to_string(simulator_steer_angle_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->angle
);
}

int simulator_steer_angle_converted_to_string_file(simulator_steer_angle_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->angle
);
}

int simulator_steer_angle_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "angle");
}

int simulator_steer_angle_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "angle");
}


int simulator_control_output_pack(
    uint8_t *dst_p,
    const simulator_control_output_t *src_p,
    size_t byte_size)
{
    if (byte_size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->estimated_velocity, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->estimated_velocity, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->torque_max_l, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->torque_max_r, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->torque_l, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->torque_l, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->torque_r, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->torque_r, 8u, 0xffu);

    return (8);
}

int simulator_control_output_unpack(
    simulator_control_output_t *dst_p,
    const uint8_t *src_p,
    size_t byte_size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (byte_size < 8u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->estimated_velocity =  unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->estimated_velocity =  (dst_p->estimated_velocity | unpack_left_shift_u16(src_p[1], 8u, 0xffu));
    dst_p->torque_max_l =  unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->torque_max_r =  unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->torque_l =  unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->torque_l =  (dst_p->torque_l | unpack_left_shift_u16(src_p[5], 8u, 0xffu));
    dst_p->torque_r =  unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->torque_r =  (dst_p->torque_r | unpack_left_shift_u16(src_p[7], 8u, 0xffu));

    return (0);
}

uint16_t simulator_control_output_estimated_velocity_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, (value - -10.0f) / 0.000686655985351339f)));
}

float simulator_control_output_estimated_velocity_decode(uint16_t value)
{
    return (((float)value * 0.000686655985351339f) + -10.0f);
}

bool simulator_control_output_estimated_velocity_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t simulator_control_output_torque_max_l_encode(float value)
{
    return (uint8_t)(canlib_max(0, canlib_min(255, value / 0.39215686274509803f)));
}

float simulator_control_output_torque_max_l_decode(uint8_t value)
{
    return ((float)value * 0.39215686274509803f);
}

bool simulator_control_output_torque_max_l_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t simulator_control_output_torque_max_r_encode(float value)
{
    return (uint8_t)(canlib_max(0, canlib_min(255, value / 0.39215686274509803f)));
}

float simulator_control_output_torque_max_r_decode(uint8_t value)
{
    return ((float)value * 0.39215686274509803f);
}

bool simulator_control_output_torque_max_r_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t simulator_control_output_torque_l_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, value / 0.0015259021896696422f)));
}

float simulator_control_output_torque_l_decode(uint16_t value)
{
    return ((float)value * 0.0015259021896696422f);
}

bool simulator_control_output_torque_l_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t simulator_control_output_torque_r_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, value / 0.0015259021896696422f)));
}

float simulator_control_output_torque_r_decode(uint16_t value)
{
    return ((float)value * 0.0015259021896696422f);
}

bool simulator_control_output_torque_r_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}


void simulator_control_output_raw_to_conversion(
    simulator_control_output_converted_t *conversion,
    float estimated_velocity,
    float torque_max_l,
    float torque_max_r,
    float torque_l,
    float torque_r
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->estimated_velocity = simulator_control_output_estimated_velocity_decode(estimated_velocity);
    conversion->torque_max_l = simulator_control_output_torque_max_l_decode(torque_max_l);
    conversion->torque_max_r = simulator_control_output_torque_max_r_decode(torque_max_r);
    conversion->torque_l = simulator_control_output_torque_l_decode(torque_l);
    conversion->torque_r = simulator_control_output_torque_r_decode(torque_r);
}


void simulator_control_output_conversion_to_raw(
    simulator_control_output_t *raw,
    float estimated_velocity,
    float torque_max_l,
    float torque_max_r,
    float torque_l,
    float torque_r
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->estimated_velocity = simulator_control_output_estimated_velocity_encode(estimated_velocity);
    raw->torque_max_l = simulator_control_output_torque_max_l_encode(torque_max_l);
    raw->torque_max_r = simulator_control_output_torque_max_r_encode(torque_max_r);
    raw->torque_l = simulator_control_output_torque_l_encode(torque_l);
    raw->torque_r = simulator_control_output_torque_r_encode(torque_r);
}


void simulator_control_output_raw_to_conversion_struct(
    simulator_control_output_converted_t *conversion, 
    const simulator_control_output_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->estimated_velocity = simulator_control_output_estimated_velocity_decode(raw->estimated_velocity);
    conversion->torque_max_l = simulator_control_output_torque_max_l_decode(raw->torque_max_l);
    conversion->torque_max_r = simulator_control_output_torque_max_r_decode(raw->torque_max_r);
    conversion->torque_l = simulator_control_output_torque_l_decode(raw->torque_l);
    conversion->torque_r = simulator_control_output_torque_r_decode(raw->torque_r);
}


void simulator_control_output_conversion_to_raw_struct(
    simulator_control_output_t *raw,
    const simulator_control_output_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->estimated_velocity = simulator_control_output_estimated_velocity_encode(conversion->estimated_velocity);
    raw->torque_max_l = simulator_control_output_torque_max_l_encode(conversion->torque_max_l);
    raw->torque_max_r = simulator_control_output_torque_max_r_encode(conversion->torque_max_r);
    raw->torque_l = simulator_control_output_torque_l_encode(conversion->torque_l);
    raw->torque_r = simulator_control_output_torque_r_encode(conversion->torque_r);
}

int simulator_control_output_converted_to_string(simulator_control_output_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->estimated_velocity,
    message->torque_max_l,
    message->torque_max_r,
    message->torque_l,
    message->torque_r
);
}

int simulator_control_output_converted_to_string_file(simulator_control_output_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->estimated_velocity,
    message->torque_max_l,
    message->torque_max_r,
    message->torque_l,
    message->torque_r
);
}

int simulator_control_output_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "estimated_velocity"","
    "torque_max_l"","
    "torque_max_r"","
    "torque_l"","
    "torque_r");
}

int simulator_control_output_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "estimated_velocity"","
    "torque_max_l"","
    "torque_max_r"","
    "torque_l"","
    "torque_r");
}


int simulator_control_status_pack(
    uint8_t *dst_p,
    const simulator_control_status_t *src_p,
    size_t byte_size)
{
    if (byte_size < 3u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->map_pw, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->map_sc, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->map_tv, 0u, 0xffu);

    return (3);
}

int simulator_control_status_unpack(
    simulator_control_status_t *dst_p,
    const uint8_t *src_p,
    size_t byte_size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (byte_size < 3u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->map_pw =  unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->map_sc =  unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->map_tv =  unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

uint8_t simulator_control_status_map_pw_encode(float value)
{
    return (uint8_t)(canlib_max(0, canlib_min(255, (value - -0.5f) / 0.01f)));
}

float simulator_control_status_map_pw_decode(uint8_t value)
{
    return (((float)value * 0.01f) + -0.5f);
}

bool simulator_control_status_map_pw_is_in_range(uint8_t value)
{
    return (value <= 150u);
}

uint8_t simulator_control_status_map_sc_encode(float value)
{
    return (uint8_t)(canlib_max(0, canlib_min(255, value / 0.01f)));
}

float simulator_control_status_map_sc_decode(uint8_t value)
{
    return ((float)value * 0.01f);
}

bool simulator_control_status_map_sc_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t simulator_control_status_map_tv_encode(float value)
{
    return (uint8_t)(canlib_max(0, canlib_min(255, value / 0.01f)));
}

float simulator_control_status_map_tv_decode(uint8_t value)
{
    return ((float)value * 0.01f);
}

bool simulator_control_status_map_tv_is_in_range(uint8_t value)
{
    return (value <= 100u);
}


void simulator_control_status_raw_to_conversion(
    simulator_control_status_converted_t *conversion,
    float map_pw,
    float map_sc,
    float map_tv
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->map_pw = simulator_control_status_map_pw_decode(map_pw);
    conversion->map_sc = simulator_control_status_map_sc_decode(map_sc);
    conversion->map_tv = simulator_control_status_map_tv_decode(map_tv);
}


void simulator_control_status_conversion_to_raw(
    simulator_control_status_t *raw,
    float map_pw,
    float map_sc,
    float map_tv
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->map_pw = simulator_control_status_map_pw_encode(map_pw);
    raw->map_sc = simulator_control_status_map_sc_encode(map_sc);
    raw->map_tv = simulator_control_status_map_tv_encode(map_tv);
}


void simulator_control_status_raw_to_conversion_struct(
    simulator_control_status_converted_t *conversion, 
    const simulator_control_status_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->map_pw = simulator_control_status_map_pw_decode(raw->map_pw);
    conversion->map_sc = simulator_control_status_map_sc_decode(raw->map_sc);
    conversion->map_tv = simulator_control_status_map_tv_decode(raw->map_tv);
}


void simulator_control_status_conversion_to_raw_struct(
    simulator_control_status_t *raw,
    const simulator_control_status_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->map_pw = simulator_control_status_map_pw_encode(conversion->map_pw);
    raw->map_sc = simulator_control_status_map_sc_encode(conversion->map_sc);
    raw->map_tv = simulator_control_status_map_tv_encode(conversion->map_tv);
}

int simulator_control_status_converted_to_string(simulator_control_status_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->map_pw,
    message->map_sc,
    message->map_tv
);
}

int simulator_control_status_converted_to_string_file(simulator_control_status_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->map_pw,
    message->map_sc,
    message->map_tv
);
}

int simulator_control_status_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "map_pw"","
    "map_sc"","
    "map_tv");
}

int simulator_control_status_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "map_pw"","
    "map_sc"","
    "map_tv");
}


int simulator_speed_pack(
    uint8_t *dst_p,
    const simulator_speed_t *src_p,
    size_t byte_size)
{
    if (byte_size < 4u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->fl, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->fl, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->fr, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->fr, 8u, 0xffu);

    return (4);
}

int simulator_speed_unpack(
    simulator_speed_t *dst_p,
    const uint8_t *src_p,
    size_t byte_size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (byte_size < 4u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->fl =  unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->fl =  (dst_p->fl | unpack_left_shift_u16(src_p[1], 8u, 0xffu));
    dst_p->fr =  unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->fr =  (dst_p->fr | unpack_left_shift_u16(src_p[3], 8u, 0xffu));

    return (0);
}

uint16_t simulator_speed_fl_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, (value - -200.0f) / 0.006103608758678569f)));
}

float simulator_speed_fl_decode(uint16_t value)
{
    return (((float)value * 0.006103608758678569f) + -200.0f);
}

bool simulator_speed_fl_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t simulator_speed_fr_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, (value - -200.0f) / 0.006103608758678569f)));
}

float simulator_speed_fr_decode(uint16_t value)
{
    return (((float)value * 0.006103608758678569f) + -200.0f);
}

bool simulator_speed_fr_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}


void simulator_speed_raw_to_conversion(
    simulator_speed_converted_t *conversion,
    float fl,
    float fr
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->fl = simulator_speed_fl_decode(fl);
    conversion->fr = simulator_speed_fr_decode(fr);
}


void simulator_speed_conversion_to_raw(
    simulator_speed_t *raw,
    float fl,
    float fr
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->fl = simulator_speed_fl_encode(fl);
    raw->fr = simulator_speed_fr_encode(fr);
}


void simulator_speed_raw_to_conversion_struct(
    simulator_speed_converted_t *conversion, 
    const simulator_speed_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->fl = simulator_speed_fl_decode(raw->fl);
    conversion->fr = simulator_speed_fr_decode(raw->fr);
}


void simulator_speed_conversion_to_raw_struct(
    simulator_speed_t *raw,
    const simulator_speed_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->fl = simulator_speed_fl_encode(conversion->fl);
    raw->fr = simulator_speed_fr_encode(conversion->fr);
}

int simulator_speed_converted_to_string(simulator_speed_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->fl,
    message->fr
);
}

int simulator_speed_converted_to_string_file(simulator_speed_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->fl,
    message->fr
);
}

int simulator_speed_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "fl"","
    "fr");
}

int simulator_speed_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "fl"","
    "fr");
}


int simulator_debug_signal_2_pack(
    uint8_t *dst_p,
    const simulator_debug_signal_2_t *src_p,
    size_t byte_size)
{
    if (byte_size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->field_1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->field_1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->field_2, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->field_2, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->field_3, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->field_3, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->field_4, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->field_4, 8u, 0xffu);

    return (8);
}

int simulator_debug_signal_2_unpack(
    simulator_debug_signal_2_t *dst_p,
    const uint8_t *src_p,
    size_t byte_size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (byte_size < 8u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->field_1 =  unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->field_1 =  (dst_p->field_1 | unpack_left_shift_u16(src_p[1], 8u, 0xffu));
    dst_p->field_2 =  unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->field_2 =  (dst_p->field_2 | unpack_left_shift_u16(src_p[3], 8u, 0xffu));
    dst_p->field_3 =  unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->field_3 =  (dst_p->field_3 | unpack_left_shift_u16(src_p[5], 8u, 0xffu));
    dst_p->field_4 =  unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->field_4 =  (dst_p->field_4 | unpack_left_shift_u16(src_p[7], 8u, 0xffu));

    return (0);
}

uint16_t simulator_debug_signal_2_field_1_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, (value - -1.0f) / 3.0518043793392844e-05f)));
}

float simulator_debug_signal_2_field_1_decode(uint16_t value)
{
    return (((float)value * 3.0518043793392844e-05f) + -1.0f);
}

bool simulator_debug_signal_2_field_1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t simulator_debug_signal_2_field_2_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, (value - -1.0f) / 3.0518043793392844e-05f)));
}

float simulator_debug_signal_2_field_2_decode(uint16_t value)
{
    return (((float)value * 3.0518043793392844e-05f) + -1.0f);
}

bool simulator_debug_signal_2_field_2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t simulator_debug_signal_2_field_3_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, (value - -1.0f) / 3.0518043793392844e-05f)));
}

float simulator_debug_signal_2_field_3_decode(uint16_t value)
{
    return (((float)value * 3.0518043793392844e-05f) + -1.0f);
}

bool simulator_debug_signal_2_field_3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t simulator_debug_signal_2_field_4_encode(float value)
{
    return (uint16_t)(canlib_max(0, canlib_min(65535, (value - -1.0f) / 3.0518043793392844e-05f)));
}

float simulator_debug_signal_2_field_4_decode(uint16_t value)
{
    return (((float)value * 3.0518043793392844e-05f) + -1.0f);
}

bool simulator_debug_signal_2_field_4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}


void simulator_debug_signal_2_raw_to_conversion(
    simulator_debug_signal_2_converted_t *conversion,
    float field_1,
    float field_2,
    float field_3,
    float field_4
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->field_1 = simulator_debug_signal_2_field_1_decode(field_1);
    conversion->field_2 = simulator_debug_signal_2_field_2_decode(field_2);
    conversion->field_3 = simulator_debug_signal_2_field_3_decode(field_3);
    conversion->field_4 = simulator_debug_signal_2_field_4_decode(field_4);
}


void simulator_debug_signal_2_conversion_to_raw(
    simulator_debug_signal_2_t *raw,
    float field_1,
    float field_2,
    float field_3,
    float field_4
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->field_1 = simulator_debug_signal_2_field_1_encode(field_1);
    raw->field_2 = simulator_debug_signal_2_field_2_encode(field_2);
    raw->field_3 = simulator_debug_signal_2_field_3_encode(field_3);
    raw->field_4 = simulator_debug_signal_2_field_4_encode(field_4);
}


void simulator_debug_signal_2_raw_to_conversion_struct(
    simulator_debug_signal_2_converted_t *conversion, 
    const simulator_debug_signal_2_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->field_1 = simulator_debug_signal_2_field_1_decode(raw->field_1);
    conversion->field_2 = simulator_debug_signal_2_field_2_decode(raw->field_2);
    conversion->field_3 = simulator_debug_signal_2_field_3_decode(raw->field_3);
    conversion->field_4 = simulator_debug_signal_2_field_4_decode(raw->field_4);
}


void simulator_debug_signal_2_conversion_to_raw_struct(
    simulator_debug_signal_2_t *raw,
    const simulator_debug_signal_2_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->field_1 = simulator_debug_signal_2_field_1_encode(conversion->field_1);
    raw->field_2 = simulator_debug_signal_2_field_2_encode(conversion->field_2);
    raw->field_3 = simulator_debug_signal_2_field_3_encode(conversion->field_3);
    raw->field_4 = simulator_debug_signal_2_field_4_encode(conversion->field_4);
}

int simulator_debug_signal_2_converted_to_string(simulator_debug_signal_2_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->field_1,
    message->field_2,
    message->field_3,
    message->field_4
);
}

int simulator_debug_signal_2_converted_to_string_file(simulator_debug_signal_2_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%" PRIu64 ","
        #endif // CANLIB_TIMESTAMP
    "%f"","
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->field_1,
    message->field_2,
    message->field_3,
    message->field_4
);
}

int simulator_debug_signal_2_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "field_1"","
    "field_2"","
    "field_3"","
    "field_4");
}

int simulator_debug_signal_2_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "field_1"","
    "field_2"","
    "field_3"","
    "field_4");
}


bool simulator_id_is_message(uint16_t id){
    switch(id){
        case SIMULATOR_IMU_ANGULAR_RATE_FRAME_ID:
        case SIMULATOR_IMU_ACCELERATION_FRAME_ID:
        case SIMULATOR_PEDAL_THROTTLE_FRAME_ID:
        case SIMULATOR_PEDAL_BRAKES_PRESSURE_FRAME_ID:
        case SIMULATOR_STEER_ANGLE_FRAME_ID:
        case SIMULATOR_CONTROL_OUTPUT_FRAME_ID:
        case SIMULATOR_CONTROL_STATUS_FRAME_ID:
        case SIMULATOR_SPEED_FRAME_ID:
        case SIMULATOR_DEBUG_SIGNAL_2_FRAME_ID:
        return true;
        break;
    default:
        return false;
    }
}

int simulator_message_name_from_id(uint16_t id, char* buffer) {
    switch (id) {
		case 1260: return sprintf(buffer, "%s", "imu_angular_rate");
		case 1261: return sprintf(buffer, "%s", "imu_acceleration");
		case 1536: return sprintf(buffer, "%s", "pedal_throttle");
		case 1544: return sprintf(buffer, "%s", "pedal_brakes_pressure");
		case 1552: return sprintf(buffer, "%s", "steer_angle");
		case 512: return sprintf(buffer, "%s", "control_output");
		case 520: return sprintf(buffer, "%s", "control_status");
		case 1560: return sprintf(buffer, "%s", "speed");
		case 1568: return sprintf(buffer, "%s", "debug_signal_2");
    }
    return 0;
}

int simulator_index_from_id(uint16_t id) {
    switch (id) {
		case 1260: return SIMULATOR_IMU_ANGULAR_RATE_INDEX;
		case 1261: return SIMULATOR_IMU_ACCELERATION_INDEX;
		case 1536: return SIMULATOR_PEDAL_THROTTLE_INDEX;
		case 1544: return SIMULATOR_PEDAL_BRAKES_PRESSURE_INDEX;
		case 1552: return SIMULATOR_STEER_ANGLE_INDEX;
		case 512: return SIMULATOR_CONTROL_OUTPUT_INDEX;
		case 520: return SIMULATOR_CONTROL_STATUS_INDEX;
		case 1560: return SIMULATOR_SPEED_INDEX;
		case 1568: return SIMULATOR_DEBUG_SIGNAL_2_INDEX;
    }
    return -1;
}

int simulator_id_from_index(int index){
    switch (index) {
		case SIMULATOR_IMU_ANGULAR_RATE_INDEX: return 1260;
		case SIMULATOR_IMU_ACCELERATION_INDEX: return 1261;
		case SIMULATOR_PEDAL_THROTTLE_INDEX: return 1536;
		case SIMULATOR_PEDAL_BRAKES_PRESSURE_INDEX: return 1544;
		case SIMULATOR_STEER_ANGLE_INDEX: return 1552;
		case SIMULATOR_CONTROL_OUTPUT_INDEX: return 512;
		case SIMULATOR_CONTROL_STATUS_INDEX: return 520;
		case SIMULATOR_SPEED_INDEX: return 1560;
		case SIMULATOR_DEBUG_SIGNAL_2_INDEX: return 1568;
    }
    return -1;
}

int simulator_to_string_from_id(uint16_t message_id,
                                void* message,
                                char* buffer
) {
    switch (message_id) {
        case 1260:
            return simulator_imu_angular_rate_converted_to_string((simulator_imu_angular_rate_converted_t*) message,
                                                buffer);
        case 1261:
            return simulator_imu_acceleration_converted_to_string((simulator_imu_acceleration_converted_t*) message,
                                                buffer);
        case 1536:
            return simulator_pedal_throttle_converted_to_string((simulator_pedal_throttle_converted_t*) message,
                                                buffer);
        case 1544:
            return simulator_pedal_brakes_pressure_converted_to_string((simulator_pedal_brakes_pressure_converted_t*) message,
                                                buffer);
        case 1552:
            return simulator_steer_angle_converted_to_string((simulator_steer_angle_converted_t*) message,
                                                buffer);
        case 512:
            return simulator_control_output_converted_to_string((simulator_control_output_converted_t*) message,
                                                buffer);
        case 520:
            return simulator_control_status_converted_to_string((simulator_control_status_converted_t*) message,
                                                buffer);
        case 1560:
            return simulator_speed_converted_to_string((simulator_speed_converted_t*) message,
                                                buffer);
        case 1568:
            return simulator_debug_signal_2_converted_to_string((simulator_debug_signal_2_converted_t*) message,
                                                buffer);
    }
	return -1;
}

int simulator_fields_from_id(uint16_t message_id, char* buffer) {
    switch (message_id) {
        case 1260:
            return simulator_imu_angular_rate_fields(buffer);
        case 1261:
            return simulator_imu_acceleration_fields(buffer);
        case 1536:
            return simulator_pedal_throttle_fields(buffer);
        case 1544:
            return simulator_pedal_brakes_pressure_fields(buffer);
        case 1552:
            return simulator_steer_angle_fields(buffer);
        case 512:
            return simulator_control_output_fields(buffer);
        case 520:
            return simulator_control_status_fields(buffer);
        case 1560:
            return simulator_speed_fields(buffer);
        case 1568:
            return simulator_debug_signal_2_fields(buffer);
    }
	return -1;
}

int simulator_to_string_file_from_id(uint16_t message_id, void* message, FILE* buffer) {
    switch (message_id) {
        case 1260:
            return simulator_imu_angular_rate_converted_to_string_file((simulator_imu_angular_rate_converted_t*) message, buffer);
        case 1261:
            return simulator_imu_acceleration_converted_to_string_file((simulator_imu_acceleration_converted_t*) message, buffer);
        case 1536:
            return simulator_pedal_throttle_converted_to_string_file((simulator_pedal_throttle_converted_t*) message, buffer);
        case 1544:
            return simulator_pedal_brakes_pressure_converted_to_string_file((simulator_pedal_brakes_pressure_converted_t*) message, buffer);
        case 1552:
            return simulator_steer_angle_converted_to_string_file((simulator_steer_angle_converted_t*) message, buffer);
        case 512:
            return simulator_control_output_converted_to_string_file((simulator_control_output_converted_t*) message, buffer);
        case 520:
            return simulator_control_status_converted_to_string_file((simulator_control_status_converted_t*) message, buffer);
        case 1560:
            return simulator_speed_converted_to_string_file((simulator_speed_converted_t*) message, buffer);
        case 1568:
            return simulator_debug_signal_2_converted_to_string_file((simulator_debug_signal_2_converted_t*) message, buffer);
    }
	return -1;
}

int simulator_fields_file_from_id(uint16_t message_id, FILE* buffer) {
    switch (message_id) {
        case 1260:
            return simulator_imu_angular_rate_fields_file(buffer);
        case 1261:
            return simulator_imu_acceleration_fields_file(buffer);
        case 1536:
            return simulator_pedal_throttle_fields_file(buffer);
        case 1544:
            return simulator_pedal_brakes_pressure_fields_file(buffer);
        case 1552:
            return simulator_steer_angle_fields_file(buffer);
        case 512:
            return simulator_control_output_fields_file(buffer);
        case 520:
            return simulator_control_status_fields_file(buffer);
        case 1560:
            return simulator_speed_fields_file(buffer);
        case 1568:
            return simulator_debug_signal_2_fields_file(buffer);
    }
	return -1;
}


void simulator_devices_deserialize_from_id(
    device_t* device,
    uint16_t message_id,
    uint8_t* data
    #ifdef CANLIB_TIMESTAMP
    , uint64_t timestamp
    #endif // CANLIB_TIMESTAMP
)
{
    switch(message_id){
        case 1260: {
            if(sizeof(simulator_imu_angular_rate_t) > device->_size_raw) {
                free(device->_raw);
                device->_raw = malloc(sizeof(simulator_imu_angular_rate_t));
                device->_size_raw = sizeof(simulator_imu_angular_rate_t);
            }
            simulator_imu_angular_rate_unpack(
                (simulator_imu_angular_rate_t*) device->_raw,
                data,
                6
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            device->message = device->_raw;
            
            if(sizeof(simulator_imu_angular_rate_converted_t) > device->_size_converted) {
                free(device->_converted);
                device->_converted = malloc(sizeof(simulator_imu_angular_rate_converted_t));
                device->_size_converted = sizeof(simulator_imu_angular_rate_converted_t);
            }
            simulator_imu_angular_rate_raw_to_conversion_struct(
                (simulator_imu_angular_rate_converted_t*) device->_converted,
                (simulator_imu_angular_rate_t*) device->_raw
            );
            device->message = device->_converted;

            return;
        }
        case 1261: {
            if(sizeof(simulator_imu_acceleration_t) > device->_size_raw) {
                free(device->_raw);
                device->_raw = malloc(sizeof(simulator_imu_acceleration_t));
                device->_size_raw = sizeof(simulator_imu_acceleration_t);
            }
            simulator_imu_acceleration_unpack(
                (simulator_imu_acceleration_t*) device->_raw,
                data,
                8
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            device->message = device->_raw;
            
            if(sizeof(simulator_imu_acceleration_converted_t) > device->_size_converted) {
                free(device->_converted);
                device->_converted = malloc(sizeof(simulator_imu_acceleration_converted_t));
                device->_size_converted = sizeof(simulator_imu_acceleration_converted_t);
            }
            simulator_imu_acceleration_raw_to_conversion_struct(
                (simulator_imu_acceleration_converted_t*) device->_converted,
                (simulator_imu_acceleration_t*) device->_raw
            );
            device->message = device->_converted;

            return;
        }
        case 1536: {
            if(sizeof(simulator_pedal_throttle_t) > device->_size_raw) {
                free(device->_raw);
                device->_raw = malloc(sizeof(simulator_pedal_throttle_t));
                device->_size_raw = sizeof(simulator_pedal_throttle_t);
            }
            simulator_pedal_throttle_unpack(
                (simulator_pedal_throttle_t*) device->_raw,
                data,
                2
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            device->message = device->_raw;
            
            if(sizeof(simulator_pedal_throttle_converted_t) > device->_size_converted) {
                free(device->_converted);
                device->_converted = malloc(sizeof(simulator_pedal_throttle_converted_t));
                device->_size_converted = sizeof(simulator_pedal_throttle_converted_t);
            }
            simulator_pedal_throttle_raw_to_conversion_struct(
                (simulator_pedal_throttle_converted_t*) device->_converted,
                (simulator_pedal_throttle_t*) device->_raw
            );
            device->message = device->_converted;

            return;
        }
        case 1544: {
            if(sizeof(simulator_pedal_brakes_pressure_t) > device->_size_raw) {
                free(device->_raw);
                device->_raw = malloc(sizeof(simulator_pedal_brakes_pressure_t));
                device->_size_raw = sizeof(simulator_pedal_brakes_pressure_t);
            }
            simulator_pedal_brakes_pressure_unpack(
                (simulator_pedal_brakes_pressure_t*) device->_raw,
                data,
                4
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            device->message = device->_raw;
            
            if(sizeof(simulator_pedal_brakes_pressure_converted_t) > device->_size_converted) {
                free(device->_converted);
                device->_converted = malloc(sizeof(simulator_pedal_brakes_pressure_converted_t));
                device->_size_converted = sizeof(simulator_pedal_brakes_pressure_converted_t);
            }
            simulator_pedal_brakes_pressure_raw_to_conversion_struct(
                (simulator_pedal_brakes_pressure_converted_t*) device->_converted,
                (simulator_pedal_brakes_pressure_t*) device->_raw
            );
            device->message = device->_converted;

            return;
        }
        case 1552: {
            if(sizeof(simulator_steer_angle_t) > device->_size_raw) {
                free(device->_raw);
                device->_raw = malloc(sizeof(simulator_steer_angle_t));
                device->_size_raw = sizeof(simulator_steer_angle_t);
            }
            simulator_steer_angle_unpack(
                (simulator_steer_angle_t*) device->_raw,
                data,
                4
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            device->message = device->_raw;
            
            if(sizeof(simulator_steer_angle_converted_t) > device->_size_converted) {
                free(device->_converted);
                device->_converted = malloc(sizeof(simulator_steer_angle_converted_t));
                device->_size_converted = sizeof(simulator_steer_angle_converted_t);
            }
            simulator_steer_angle_raw_to_conversion_struct(
                (simulator_steer_angle_converted_t*) device->_converted,
                (simulator_steer_angle_t*) device->_raw
            );
            device->message = device->_converted;

            return;
        }
        case 512: {
            if(sizeof(simulator_control_output_t) > device->_size_raw) {
                free(device->_raw);
                device->_raw = malloc(sizeof(simulator_control_output_t));
                device->_size_raw = sizeof(simulator_control_output_t);
            }
            simulator_control_output_unpack(
                (simulator_control_output_t*) device->_raw,
                data,
                8
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            device->message = device->_raw;
            
            if(sizeof(simulator_control_output_converted_t) > device->_size_converted) {
                free(device->_converted);
                device->_converted = malloc(sizeof(simulator_control_output_converted_t));
                device->_size_converted = sizeof(simulator_control_output_converted_t);
            }
            simulator_control_output_raw_to_conversion_struct(
                (simulator_control_output_converted_t*) device->_converted,
                (simulator_control_output_t*) device->_raw
            );
            device->message = device->_converted;

            return;
        }
        case 520: {
            if(sizeof(simulator_control_status_t) > device->_size_raw) {
                free(device->_raw);
                device->_raw = malloc(sizeof(simulator_control_status_t));
                device->_size_raw = sizeof(simulator_control_status_t);
            }
            simulator_control_status_unpack(
                (simulator_control_status_t*) device->_raw,
                data,
                3
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            device->message = device->_raw;
            
            if(sizeof(simulator_control_status_converted_t) > device->_size_converted) {
                free(device->_converted);
                device->_converted = malloc(sizeof(simulator_control_status_converted_t));
                device->_size_converted = sizeof(simulator_control_status_converted_t);
            }
            simulator_control_status_raw_to_conversion_struct(
                (simulator_control_status_converted_t*) device->_converted,
                (simulator_control_status_t*) device->_raw
            );
            device->message = device->_converted;

            return;
        }
        case 1560: {
            if(sizeof(simulator_speed_t) > device->_size_raw) {
                free(device->_raw);
                device->_raw = malloc(sizeof(simulator_speed_t));
                device->_size_raw = sizeof(simulator_speed_t);
            }
            simulator_speed_unpack(
                (simulator_speed_t*) device->_raw,
                data,
                4
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            device->message = device->_raw;
            
            if(sizeof(simulator_speed_converted_t) > device->_size_converted) {
                free(device->_converted);
                device->_converted = malloc(sizeof(simulator_speed_converted_t));
                device->_size_converted = sizeof(simulator_speed_converted_t);
            }
            simulator_speed_raw_to_conversion_struct(
                (simulator_speed_converted_t*) device->_converted,
                (simulator_speed_t*) device->_raw
            );
            device->message = device->_converted;

            return;
        }
        case 1568: {
            if(sizeof(simulator_debug_signal_2_t) > device->_size_raw) {
                free(device->_raw);
                device->_raw = malloc(sizeof(simulator_debug_signal_2_t));
                device->_size_raw = sizeof(simulator_debug_signal_2_t);
            }
            simulator_debug_signal_2_unpack(
                (simulator_debug_signal_2_t*) device->_raw,
                data,
                8
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            device->message = device->_raw;
            
            if(sizeof(simulator_debug_signal_2_converted_t) > device->_size_converted) {
                free(device->_converted);
                device->_converted = malloc(sizeof(simulator_debug_signal_2_converted_t));
                device->_size_converted = sizeof(simulator_debug_signal_2_converted_t);
            }
            simulator_debug_signal_2_raw_to_conversion_struct(
                (simulator_debug_signal_2_converted_t*) device->_converted,
                (simulator_debug_signal_2_t*) device->_raw
            );
            device->message = device->_converted;

            return;
        }

    }
}
int simulator_serialize_from_id(
    void* converted_struct_pointer,
    uint16_t message_id,
    uint8_t* data
)
{
    switch(message_id){

        case 1260: {
            simulator_imu_angular_rate_t raw;
            simulator_imu_angular_rate_conversion_to_raw_struct(
                        (simulator_imu_angular_rate_t*) &raw,
                        (simulator_imu_angular_rate_converted_t*) converted_struct_pointer
            );
            return simulator_imu_angular_rate_pack(data, &raw, 6);
        }
        case 1261: {
            simulator_imu_acceleration_t raw;
            simulator_imu_acceleration_conversion_to_raw_struct(
                        (simulator_imu_acceleration_t*) &raw,
                        (simulator_imu_acceleration_converted_t*) converted_struct_pointer
            );
            return simulator_imu_acceleration_pack(data, &raw, 8);
        }
        case 1536: {
            simulator_pedal_throttle_t raw;
            simulator_pedal_throttle_conversion_to_raw_struct(
                        (simulator_pedal_throttle_t*) &raw,
                        (simulator_pedal_throttle_converted_t*) converted_struct_pointer
            );
            return simulator_pedal_throttle_pack(data, &raw, 2);
        }
        case 1544: {
            simulator_pedal_brakes_pressure_t raw;
            simulator_pedal_brakes_pressure_conversion_to_raw_struct(
                        (simulator_pedal_brakes_pressure_t*) &raw,
                        (simulator_pedal_brakes_pressure_converted_t*) converted_struct_pointer
            );
            return simulator_pedal_brakes_pressure_pack(data, &raw, 4);
        }
        case 1552: {
            simulator_steer_angle_t raw;
            simulator_steer_angle_conversion_to_raw_struct(
                        (simulator_steer_angle_t*) &raw,
                        (simulator_steer_angle_converted_t*) converted_struct_pointer
            );
            return simulator_steer_angle_pack(data, &raw, 4);
        }
        case 512: {
            simulator_control_output_t raw;
            simulator_control_output_conversion_to_raw_struct(
                        (simulator_control_output_t*) &raw,
                        (simulator_control_output_converted_t*) converted_struct_pointer
            );
            return simulator_control_output_pack(data, &raw, 8);
        }
        case 520: {
            simulator_control_status_t raw;
            simulator_control_status_conversion_to_raw_struct(
                        (simulator_control_status_t*) &raw,
                        (simulator_control_status_converted_t*) converted_struct_pointer
            );
            return simulator_control_status_pack(data, &raw, 3);
        }
        case 1560: {
            simulator_speed_t raw;
            simulator_speed_conversion_to_raw_struct(
                        (simulator_speed_t*) &raw,
                        (simulator_speed_converted_t*) converted_struct_pointer
            );
            return simulator_speed_pack(data, &raw, 4);
        }
        case 1568: {
            simulator_debug_signal_2_t raw;
            simulator_debug_signal_2_conversion_to_raw_struct(
                        (simulator_debug_signal_2_t*) &raw,
                        (simulator_debug_signal_2_converted_t*) converted_struct_pointer
            );
            return simulator_debug_signal_2_pack(data, &raw, 8);
        }
    }
    return -1;
}
