/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Thu Jun  1 20:50:25 2023.
 */

#include <string.h>

#include "network.h"

static uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int bms_board_status_pack(
    uint8_t *dst_p,
    const bms_board_status_t *src_p,
    size_t size)
{
    if (size < 17u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 17);

    dst_p[0] |= pack_left_shift_u8(src_p->errors_can_comm, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->errors_ltc_comm, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->errors_temp_comm_0, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->errors_temp_comm_1, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->errors_temp_comm_2, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->errors_temp_comm_3, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->errors_temp_comm_4, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->errors_temp_comm_5, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->errors_open_wire, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->balancing_status, 1u, 0xfeu);
    dst_p[2] |= pack_right_shift_u8(src_p->balancing_status, 7u, 0x01u);

    return (17);
}

int bms_board_status_unpack(
    bms_board_status_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (size < 17u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->errors_can_comm =  unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->errors_ltc_comm =  unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->errors_temp_comm_0 =  unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->errors_temp_comm_1 =  unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->errors_temp_comm_2 =  unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->errors_temp_comm_3 =  unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->errors_temp_comm_4 =  unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->errors_temp_comm_5 =  unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->errors_open_wire =  unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->balancing_status = (bms_board_status_balancing_status) unpack_right_shift_u8(src_p[1], 1u, 0xfeu);
    dst_p->balancing_status |= (bms_board_status_balancing_status) unpack_left_shift_u8(src_p[2], 7u, 0x01u);

    return (0);
}

bool bms_board_status_errors_can_comm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_board_status_errors_ltc_comm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_board_status_errors_temp_comm_0_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_board_status_errors_temp_comm_1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_board_status_errors_temp_comm_2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_board_status_errors_temp_comm_3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_board_status_errors_temp_comm_4_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_board_status_errors_temp_comm_5_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_board_status_errors_open_wire_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_board_status_balancing_status_is_in_range(uint8_t value)
{
    return (value <= 2u);
}


void bms_board_status_raw_to_conversion(
    bms_board_status_converted_t *conversion,
    uint8_t errors_can_comm,
    uint8_t errors_ltc_comm,
    uint8_t errors_temp_comm_0,
    uint8_t errors_temp_comm_1,
    uint8_t errors_temp_comm_2,
    uint8_t errors_temp_comm_3,
    uint8_t errors_temp_comm_4,
    uint8_t errors_temp_comm_5,
    uint8_t errors_open_wire,
    bms_board_status_balancing_status balancing_status
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->errors_can_comm = errors_can_comm; 
    conversion->errors_ltc_comm = errors_ltc_comm; 
    conversion->errors_temp_comm_0 = errors_temp_comm_0; 
    conversion->errors_temp_comm_1 = errors_temp_comm_1; 
    conversion->errors_temp_comm_2 = errors_temp_comm_2; 
    conversion->errors_temp_comm_3 = errors_temp_comm_3; 
    conversion->errors_temp_comm_4 = errors_temp_comm_4; 
    conversion->errors_temp_comm_5 = errors_temp_comm_5; 
    conversion->errors_open_wire = errors_open_wire; 
    conversion->balancing_status = balancing_status; 
}


void bms_board_status_conversion_to_raw(
    bms_board_status_t *raw,
    uint8_t errors_can_comm,
    uint8_t errors_ltc_comm,
    uint8_t errors_temp_comm_0,
    uint8_t errors_temp_comm_1,
    uint8_t errors_temp_comm_2,
    uint8_t errors_temp_comm_3,
    uint8_t errors_temp_comm_4,
    uint8_t errors_temp_comm_5,
    uint8_t errors_open_wire,
    bms_board_status_balancing_status balancing_status
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->errors_can_comm = errors_can_comm; 
    raw->errors_ltc_comm = errors_ltc_comm; 
    raw->errors_temp_comm_0 = errors_temp_comm_0; 
    raw->errors_temp_comm_1 = errors_temp_comm_1; 
    raw->errors_temp_comm_2 = errors_temp_comm_2; 
    raw->errors_temp_comm_3 = errors_temp_comm_3; 
    raw->errors_temp_comm_4 = errors_temp_comm_4; 
    raw->errors_temp_comm_5 = errors_temp_comm_5; 
    raw->errors_open_wire = errors_open_wire; 
    raw->balancing_status = balancing_status; 
}


void bms_board_status_raw_to_conversion_struct(
    bms_board_status_converted_t *conversion, 
    const bms_board_status_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->errors_can_comm = raw->errors_can_comm; 
    conversion->errors_ltc_comm = raw->errors_ltc_comm; 
    conversion->errors_temp_comm_0 = raw->errors_temp_comm_0; 
    conversion->errors_temp_comm_1 = raw->errors_temp_comm_1; 
    conversion->errors_temp_comm_2 = raw->errors_temp_comm_2; 
    conversion->errors_temp_comm_3 = raw->errors_temp_comm_3; 
    conversion->errors_temp_comm_4 = raw->errors_temp_comm_4; 
    conversion->errors_temp_comm_5 = raw->errors_temp_comm_5; 
    conversion->errors_open_wire = raw->errors_open_wire; 
    conversion->balancing_status = raw->balancing_status; 
}


void bms_board_status_conversion_to_raw_struct(
    bms_board_status_t *raw,
    const bms_board_status_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->errors_can_comm = conversion->errors_can_comm; 
    raw->errors_ltc_comm = conversion->errors_ltc_comm; 
    raw->errors_temp_comm_0 = conversion->errors_temp_comm_0; 
    raw->errors_temp_comm_1 = conversion->errors_temp_comm_1; 
    raw->errors_temp_comm_2 = conversion->errors_temp_comm_2; 
    raw->errors_temp_comm_3 = conversion->errors_temp_comm_3; 
    raw->errors_temp_comm_4 = conversion->errors_temp_comm_4; 
    raw->errors_temp_comm_5 = conversion->errors_temp_comm_5; 
    raw->errors_open_wire = conversion->errors_open_wire; 
    raw->balancing_status = conversion->balancing_status; 
}

int bms_board_status_to_string(bms_board_status_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  "",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->errors_can_comm,
    message->errors_ltc_comm,
    message->errors_temp_comm_0,
    message->errors_temp_comm_1,
    message->errors_temp_comm_2,
    message->errors_temp_comm_3,
    message->errors_temp_comm_4,
    message->errors_temp_comm_5,
    message->errors_open_wire,
    message->balancing_status
);
}

int bms_board_status_to_string_file(bms_board_status_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  "",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->errors_can_comm,
    message->errors_ltc_comm,
    message->errors_temp_comm_0,
    message->errors_temp_comm_1,
    message->errors_temp_comm_2,
    message->errors_temp_comm_3,
    message->errors_temp_comm_4,
    message->errors_temp_comm_5,
    message->errors_open_wire,
    message->balancing_status
);
}

int bms_board_status_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "errors_can_comm"","
    "errors_ltc_comm"","
    "errors_temp_comm_0"","
    "errors_temp_comm_1"","
    "errors_temp_comm_2"","
    "errors_temp_comm_3"","
    "errors_temp_comm_4"","
    "errors_temp_comm_5"","
    "errors_open_wire"","
    "balancing_status");
}

int bms_board_status_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "errors_can_comm"","
    "errors_ltc_comm"","
    "errors_temp_comm_0"","
    "errors_temp_comm_1"","
    "errors_temp_comm_2"","
    "errors_temp_comm_3"","
    "errors_temp_comm_4"","
    "errors_temp_comm_5"","
    "errors_open_wire"","
    "balancing_status");
}

int bms_board_status_balancing_status_enum_to_string(bms_board_status_balancing_status value, char *buffer){
    switch(value)
    {
		case 0: return sprintf(buffer, "OFF");
		case 1: return sprintf(buffer, "DISCHARGE");

    }
    sprintf(buffer, "_UNKNOWN_");
    return 0;
}
int bms_temperatures_pack(
    uint8_t *dst_p,
    const bms_temperatures_t *src_p,
    size_t size)
{
    if (size < 112u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 112);

    dst_p[0] |= pack_left_shift_u16(src_p->start_index, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->start_index, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp0, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp0, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->temp1, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->temp1, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->temp2, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->temp2, 8u, 0xffu);
    dst_p[8] |= pack_left_shift_u16(src_p->temp3, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u16(src_p->temp3, 8u, 0xffu);
    dst_p[10] |= pack_left_shift_u16(src_p->temp4, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u16(src_p->temp4, 8u, 0xffu);
    dst_p[12] |= pack_left_shift_u16(src_p->temp5, 0u, 0xffu);
    dst_p[13] |= pack_right_shift_u16(src_p->temp5, 8u, 0xffu);

    return (112);
}

int bms_temperatures_unpack(
    bms_temperatures_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (size < 112u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->start_index =  unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->start_index |=  unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp0 =  unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp0 |=  unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->temp1 =  unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->temp1 |=  unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->temp2 =  unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->temp2 |=  unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->temp3 =  unpack_right_shift_u16(src_p[8], 0u, 0xffu);
    dst_p->temp3 |=  unpack_left_shift_u16(src_p[9], 8u, 0xffu);
    dst_p->temp4 =  unpack_right_shift_u16(src_p[10], 0u, 0xffu);
    dst_p->temp4 |=  unpack_left_shift_u16(src_p[11], 8u, 0xffu);
    dst_p->temp5 =  unpack_right_shift_u16(src_p[12], 0u, 0xffu);
    dst_p->temp5 |=  unpack_left_shift_u16(src_p[13], 8u, 0xffu);

    return (0);
}

bool bms_temperatures_start_index_is_in_range(uint16_t value)
{
    return (value <= 256u);
}

uint16_t bms_temperatures_temp0_encode(double value)
{
    return (uint16_t)((value - -20.0) / 0.39215686274509803);
}

double bms_temperatures_temp0_decode(uint16_t value)
{
    return (((double)value * 0.39215686274509803) + -20.0);
}

bool bms_temperatures_temp0_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint16_t bms_temperatures_temp1_encode(double value)
{
    return (uint16_t)((value - -20.0) / 0.39215686274509803);
}

double bms_temperatures_temp1_decode(uint16_t value)
{
    return (((double)value * 0.39215686274509803) + -20.0);
}

bool bms_temperatures_temp1_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint16_t bms_temperatures_temp2_encode(double value)
{
    return (uint16_t)((value - -20.0) / 0.39215686274509803);
}

double bms_temperatures_temp2_decode(uint16_t value)
{
    return (((double)value * 0.39215686274509803) + -20.0);
}

bool bms_temperatures_temp2_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint16_t bms_temperatures_temp3_encode(double value)
{
    return (uint16_t)((value - -20.0) / 0.39215686274509803);
}

double bms_temperatures_temp3_decode(uint16_t value)
{
    return (((double)value * 0.39215686274509803) + -20.0);
}

bool bms_temperatures_temp3_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint16_t bms_temperatures_temp4_encode(double value)
{
    return (uint16_t)((value - -20.0) / 0.39215686274509803);
}

double bms_temperatures_temp4_decode(uint16_t value)
{
    return (((double)value * 0.39215686274509803) + -20.0);
}

bool bms_temperatures_temp4_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint16_t bms_temperatures_temp5_encode(double value)
{
    return (uint16_t)((value - -20.0) / 0.39215686274509803);
}

double bms_temperatures_temp5_decode(uint16_t value)
{
    return (((double)value * 0.39215686274509803) + -20.0);
}

bool bms_temperatures_temp5_is_in_range(uint16_t value)
{
    return (value <= 255u);
}


void bms_temperatures_raw_to_conversion(
    bms_temperatures_converted_t *conversion,
    uint16_t start_index,
    float temp0,
    float temp1,
    float temp2,
    float temp3,
    float temp4,
    float temp5
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->start_index = start_index; 
    conversion->temp0 = bms_temperatures_temp0_decode(temp0); 
    conversion->temp1 = bms_temperatures_temp1_decode(temp1); 
    conversion->temp2 = bms_temperatures_temp2_decode(temp2); 
    conversion->temp3 = bms_temperatures_temp3_decode(temp3); 
    conversion->temp4 = bms_temperatures_temp4_decode(temp4); 
    conversion->temp5 = bms_temperatures_temp5_decode(temp5); 
}


void bms_temperatures_conversion_to_raw(
    bms_temperatures_t *raw,
    uint16_t start_index,
    float temp0,
    float temp1,
    float temp2,
    float temp3,
    float temp4,
    float temp5
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->start_index = start_index; 
    raw->temp0 = bms_temperatures_temp0_encode(temp0); 
    raw->temp1 = bms_temperatures_temp1_encode(temp1); 
    raw->temp2 = bms_temperatures_temp2_encode(temp2); 
    raw->temp3 = bms_temperatures_temp3_encode(temp3); 
    raw->temp4 = bms_temperatures_temp4_encode(temp4); 
    raw->temp5 = bms_temperatures_temp5_encode(temp5); 
}


void bms_temperatures_raw_to_conversion_struct(
    bms_temperatures_converted_t *conversion, 
    const bms_temperatures_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->start_index = raw->start_index; 
    conversion->temp0 = bms_temperatures_temp0_decode(raw->temp0); 
    conversion->temp1 = bms_temperatures_temp1_decode(raw->temp1); 
    conversion->temp2 = bms_temperatures_temp2_decode(raw->temp2); 
    conversion->temp3 = bms_temperatures_temp3_decode(raw->temp3); 
    conversion->temp4 = bms_temperatures_temp4_decode(raw->temp4); 
    conversion->temp5 = bms_temperatures_temp5_decode(raw->temp5); 
}


void bms_temperatures_conversion_to_raw_struct(
    bms_temperatures_t *raw,
    const bms_temperatures_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->start_index = conversion->start_index; 
    raw->temp0 = bms_temperatures_temp0_encode(conversion->temp0); 
    raw->temp1 = bms_temperatures_temp1_encode(conversion->temp1); 
    raw->temp2 = bms_temperatures_temp2_encode(conversion->temp2); 
    raw->temp3 = bms_temperatures_temp3_encode(conversion->temp3); 
    raw->temp4 = bms_temperatures_temp4_encode(conversion->temp4); 
    raw->temp5 = bms_temperatures_temp5_encode(conversion->temp5); 
}

int bms_temperatures_converted_to_string(bms_temperatures_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu16 ""","
    "%f"","
    "%f"","
    "%f"","
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->start_index,
    message->temp0,
    message->temp1,
    message->temp2,
    message->temp3,
    message->temp4,
    message->temp5
);
}

int bms_temperatures_converted_to_string_file(bms_temperatures_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu16 ""","
    "%f"","
    "%f"","
    "%f"","
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->start_index,
    message->temp0,
    message->temp1,
    message->temp2,
    message->temp3,
    message->temp4,
    message->temp5
);
}

int bms_temperatures_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "start_index"","
    "temp0"","
    "temp1"","
    "temp2"","
    "temp3"","
    "temp4"","
    "temp5");
}

int bms_temperatures_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "start_index"","
    "temp0"","
    "temp1"","
    "temp2"","
    "temp3"","
    "temp4"","
    "temp5");
}


int bms_voltages_pack(
    uint8_t *dst_p,
    const bms_voltages_t *src_p,
    size_t size)
{
    if (size < 40u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 40);

    dst_p[0] |= pack_left_shift_u16(src_p->start_index, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->start_index, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->voltage0, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->voltage1, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->voltage2, 0u, 0xffu);

    return (40);
}

int bms_voltages_unpack(
    bms_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (size < 40u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->start_index =  unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->start_index |=  unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->voltage0 =  unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->voltage1 =  unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->voltage2 =  unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

bool bms_voltages_start_index_is_in_range(uint16_t value)
{
    return (value <= 256u);
}

uint8_t bms_voltages_voltage0_encode(double value)
{
    return (uint8_t)(value / 0.7142857142857143);
}

double bms_voltages_voltage0_decode(uint8_t value)
{
    return ((double)value * 0.7142857142857143);
}

bool bms_voltages_voltage0_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t bms_voltages_voltage1_encode(double value)
{
    return (uint8_t)(value / 0.7142857142857143);
}

double bms_voltages_voltage1_decode(uint8_t value)
{
    return ((double)value * 0.7142857142857143);
}

bool bms_voltages_voltage1_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t bms_voltages_voltage2_encode(double value)
{
    return (uint8_t)(value / 0.7142857142857143);
}

double bms_voltages_voltage2_decode(uint8_t value)
{
    return ((double)value * 0.7142857142857143);
}

bool bms_voltages_voltage2_is_in_range(uint8_t value)
{
    return (value <= 7u);
}


void bms_voltages_raw_to_conversion(
    bms_voltages_converted_t *conversion,
    uint16_t start_index,
    float voltage0,
    float voltage1,
    float voltage2
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->start_index = start_index; 
    conversion->voltage0 = bms_voltages_voltage0_decode(voltage0); 
    conversion->voltage1 = bms_voltages_voltage1_decode(voltage1); 
    conversion->voltage2 = bms_voltages_voltage2_decode(voltage2); 
}


void bms_voltages_conversion_to_raw(
    bms_voltages_t *raw,
    uint16_t start_index,
    float voltage0,
    float voltage1,
    float voltage2
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->start_index = start_index; 
    raw->voltage0 = bms_voltages_voltage0_encode(voltage0); 
    raw->voltage1 = bms_voltages_voltage1_encode(voltage1); 
    raw->voltage2 = bms_voltages_voltage2_encode(voltage2); 
}


void bms_voltages_raw_to_conversion_struct(
    bms_voltages_converted_t *conversion, 
    const bms_voltages_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->start_index = raw->start_index; 
    conversion->voltage0 = bms_voltages_voltage0_decode(raw->voltage0); 
    conversion->voltage1 = bms_voltages_voltage1_decode(raw->voltage1); 
    conversion->voltage2 = bms_voltages_voltage2_decode(raw->voltage2); 
}


void bms_voltages_conversion_to_raw_struct(
    bms_voltages_t *raw,
    const bms_voltages_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->start_index = conversion->start_index; 
    raw->voltage0 = bms_voltages_voltage0_encode(conversion->voltage0); 
    raw->voltage1 = bms_voltages_voltage1_encode(conversion->voltage1); 
    raw->voltage2 = bms_voltages_voltage2_encode(conversion->voltage2); 
}

int bms_voltages_converted_to_string(bms_voltages_converted_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu16 ""","
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->start_index,
    message->voltage0,
    message->voltage1,
    message->voltage2
);
}

int bms_voltages_converted_to_string_file(bms_voltages_converted_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu16 ""","
    "%f"","
    "%f"","
    "%f",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->start_index,
    message->voltage0,
    message->voltage1,
    message->voltage2
);
}

int bms_voltages_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "start_index"","
    "voltage0"","
    "voltage1"","
    "voltage2");
}

int bms_voltages_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "start_index"","
    "voltage0"","
    "voltage1"","
    "voltage2");
}


int bms_balancing_pack(
    uint8_t *dst_p,
    const bms_balancing_t *src_p,
    size_t size)
{
    if (size < 34u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 34);

    dst_p[0] |= pack_left_shift_u16(src_p->board_index, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->board_index, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->cells_cell0, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->cells_cell1, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->cells_cell2, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->cells_cell3, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->cells_cell4, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->cells_cell5, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->cells_cell6, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->cells_cell7, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->cells_cell8, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->cells_cell9, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->cells_cell10, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->cells_cell11, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->cells_cell12, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->cells_cell13, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->cells_cell14, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->cells_cell15, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u8(src_p->cells_cell16, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->cells_cell17, 1u, 0x02u);

    return (34);
}

int bms_balancing_unpack(
    bms_balancing_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (size < 34u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->board_index =  unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->board_index |=  unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cells_cell0 =  unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->cells_cell1 =  unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->cells_cell2 =  unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->cells_cell3 =  unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->cells_cell4 =  unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->cells_cell5 =  unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->cells_cell6 =  unpack_right_shift_u8(src_p[2], 6u, 0x40u);
    dst_p->cells_cell7 =  unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->cells_cell8 =  unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->cells_cell9 =  unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->cells_cell10 =  unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->cells_cell11 =  unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->cells_cell12 =  unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->cells_cell13 =  unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->cells_cell14 =  unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->cells_cell15 =  unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->cells_cell16 =  unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->cells_cell17 =  unpack_right_shift_u8(src_p[4], 1u, 0x02u);

    return (0);
}

bool bms_balancing_board_index_is_in_range(uint16_t value)
{
    return (value <= 256u);
}

bool bms_balancing_cells_cell0_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell4_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell5_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell6_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell7_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell8_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell9_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell10_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell11_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell12_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell13_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell14_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell15_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell16_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms_balancing_cells_cell17_is_in_range(uint8_t value)
{
    return (value <= 1u);
}


void bms_balancing_raw_to_conversion(
    bms_balancing_converted_t *conversion,
    uint16_t board_index,
    uint8_t cells_cell0,
    uint8_t cells_cell1,
    uint8_t cells_cell2,
    uint8_t cells_cell3,
    uint8_t cells_cell4,
    uint8_t cells_cell5,
    uint8_t cells_cell6,
    uint8_t cells_cell7,
    uint8_t cells_cell8,
    uint8_t cells_cell9,
    uint8_t cells_cell10,
    uint8_t cells_cell11,
    uint8_t cells_cell12,
    uint8_t cells_cell13,
    uint8_t cells_cell14,
    uint8_t cells_cell15,
    uint8_t cells_cell16,
    uint8_t cells_cell17
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->board_index = board_index; 
    conversion->cells_cell0 = cells_cell0; 
    conversion->cells_cell1 = cells_cell1; 
    conversion->cells_cell2 = cells_cell2; 
    conversion->cells_cell3 = cells_cell3; 
    conversion->cells_cell4 = cells_cell4; 
    conversion->cells_cell5 = cells_cell5; 
    conversion->cells_cell6 = cells_cell6; 
    conversion->cells_cell7 = cells_cell7; 
    conversion->cells_cell8 = cells_cell8; 
    conversion->cells_cell9 = cells_cell9; 
    conversion->cells_cell10 = cells_cell10; 
    conversion->cells_cell11 = cells_cell11; 
    conversion->cells_cell12 = cells_cell12; 
    conversion->cells_cell13 = cells_cell13; 
    conversion->cells_cell14 = cells_cell14; 
    conversion->cells_cell15 = cells_cell15; 
    conversion->cells_cell16 = cells_cell16; 
    conversion->cells_cell17 = cells_cell17; 
}


void bms_balancing_conversion_to_raw(
    bms_balancing_t *raw,
    uint16_t board_index,
    uint8_t cells_cell0,
    uint8_t cells_cell1,
    uint8_t cells_cell2,
    uint8_t cells_cell3,
    uint8_t cells_cell4,
    uint8_t cells_cell5,
    uint8_t cells_cell6,
    uint8_t cells_cell7,
    uint8_t cells_cell8,
    uint8_t cells_cell9,
    uint8_t cells_cell10,
    uint8_t cells_cell11,
    uint8_t cells_cell12,
    uint8_t cells_cell13,
    uint8_t cells_cell14,
    uint8_t cells_cell15,
    uint8_t cells_cell16,
    uint8_t cells_cell17
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->board_index = board_index; 
    raw->cells_cell0 = cells_cell0; 
    raw->cells_cell1 = cells_cell1; 
    raw->cells_cell2 = cells_cell2; 
    raw->cells_cell3 = cells_cell3; 
    raw->cells_cell4 = cells_cell4; 
    raw->cells_cell5 = cells_cell5; 
    raw->cells_cell6 = cells_cell6; 
    raw->cells_cell7 = cells_cell7; 
    raw->cells_cell8 = cells_cell8; 
    raw->cells_cell9 = cells_cell9; 
    raw->cells_cell10 = cells_cell10; 
    raw->cells_cell11 = cells_cell11; 
    raw->cells_cell12 = cells_cell12; 
    raw->cells_cell13 = cells_cell13; 
    raw->cells_cell14 = cells_cell14; 
    raw->cells_cell15 = cells_cell15; 
    raw->cells_cell16 = cells_cell16; 
    raw->cells_cell17 = cells_cell17; 
}


void bms_balancing_raw_to_conversion_struct(
    bms_balancing_converted_t *conversion, 
    const bms_balancing_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->board_index = raw->board_index; 
    conversion->cells_cell0 = raw->cells_cell0; 
    conversion->cells_cell1 = raw->cells_cell1; 
    conversion->cells_cell2 = raw->cells_cell2; 
    conversion->cells_cell3 = raw->cells_cell3; 
    conversion->cells_cell4 = raw->cells_cell4; 
    conversion->cells_cell5 = raw->cells_cell5; 
    conversion->cells_cell6 = raw->cells_cell6; 
    conversion->cells_cell7 = raw->cells_cell7; 
    conversion->cells_cell8 = raw->cells_cell8; 
    conversion->cells_cell9 = raw->cells_cell9; 
    conversion->cells_cell10 = raw->cells_cell10; 
    conversion->cells_cell11 = raw->cells_cell11; 
    conversion->cells_cell12 = raw->cells_cell12; 
    conversion->cells_cell13 = raw->cells_cell13; 
    conversion->cells_cell14 = raw->cells_cell14; 
    conversion->cells_cell15 = raw->cells_cell15; 
    conversion->cells_cell16 = raw->cells_cell16; 
    conversion->cells_cell17 = raw->cells_cell17; 
}


void bms_balancing_conversion_to_raw_struct(
    bms_balancing_t *raw,
    const bms_balancing_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->board_index = conversion->board_index; 
    raw->cells_cell0 = conversion->cells_cell0; 
    raw->cells_cell1 = conversion->cells_cell1; 
    raw->cells_cell2 = conversion->cells_cell2; 
    raw->cells_cell3 = conversion->cells_cell3; 
    raw->cells_cell4 = conversion->cells_cell4; 
    raw->cells_cell5 = conversion->cells_cell5; 
    raw->cells_cell6 = conversion->cells_cell6; 
    raw->cells_cell7 = conversion->cells_cell7; 
    raw->cells_cell8 = conversion->cells_cell8; 
    raw->cells_cell9 = conversion->cells_cell9; 
    raw->cells_cell10 = conversion->cells_cell10; 
    raw->cells_cell11 = conversion->cells_cell11; 
    raw->cells_cell12 = conversion->cells_cell12; 
    raw->cells_cell13 = conversion->cells_cell13; 
    raw->cells_cell14 = conversion->cells_cell14; 
    raw->cells_cell15 = conversion->cells_cell15; 
    raw->cells_cell16 = conversion->cells_cell16; 
    raw->cells_cell17 = conversion->cells_cell17; 
}

int bms_balancing_to_string(bms_balancing_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu16 ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  "",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->board_index,
    message->cells_cell0,
    message->cells_cell1,
    message->cells_cell2,
    message->cells_cell3,
    message->cells_cell4,
    message->cells_cell5,
    message->cells_cell6,
    message->cells_cell7,
    message->cells_cell8,
    message->cells_cell9,
    message->cells_cell10,
    message->cells_cell11,
    message->cells_cell12,
    message->cells_cell13,
    message->cells_cell14,
    message->cells_cell15,
    message->cells_cell16,
    message->cells_cell17
);
}

int bms_balancing_to_string_file(bms_balancing_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu16 ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  ""","
    "%" PRIu8  "",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->board_index,
    message->cells_cell0,
    message->cells_cell1,
    message->cells_cell2,
    message->cells_cell3,
    message->cells_cell4,
    message->cells_cell5,
    message->cells_cell6,
    message->cells_cell7,
    message->cells_cell8,
    message->cells_cell9,
    message->cells_cell10,
    message->cells_cell11,
    message->cells_cell12,
    message->cells_cell13,
    message->cells_cell14,
    message->cells_cell15,
    message->cells_cell16,
    message->cells_cell17
);
}

int bms_balancing_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "board_index"","
    "cells_cell0"","
    "cells_cell1"","
    "cells_cell2"","
    "cells_cell3"","
    "cells_cell4"","
    "cells_cell5"","
    "cells_cell6"","
    "cells_cell7"","
    "cells_cell8"","
    "cells_cell9"","
    "cells_cell10"","
    "cells_cell11"","
    "cells_cell12"","
    "cells_cell13"","
    "cells_cell14"","
    "cells_cell15"","
    "cells_cell16"","
    "cells_cell17");
}

int bms_balancing_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "board_index"","
    "cells_cell0"","
    "cells_cell1"","
    "cells_cell2"","
    "cells_cell3"","
    "cells_cell4"","
    "cells_cell5"","
    "cells_cell6"","
    "cells_cell7"","
    "cells_cell8"","
    "cells_cell9"","
    "cells_cell10"","
    "cells_cell11"","
    "cells_cell12"","
    "cells_cell13"","
    "cells_cell14"","
    "cells_cell15"","
    "cells_cell16"","
    "cells_cell17");
}


int bms_fw_update_pack(
    uint8_t *dst_p,
    const bms_fw_update_t *src_p,
    size_t size)
{
    if (size < 16u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 16);

    dst_p[0] |= pack_left_shift_u16(src_p->board_index, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->board_index, 8u, 0xffu);

    return (16);
}

int bms_fw_update_unpack(
    bms_fw_update_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAMP
    )
{
    if (size < 16u) {
        return (-EINVAL);
    }
#ifdef CANLIB_TIMESTAMP
    dst_p->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP

    dst_p->board_index =  unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->board_index |=  unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

bool bms_fw_update_board_index_is_in_range(uint16_t value)
{
    return (value <= 256u);
}


void bms_fw_update_raw_to_conversion(
    bms_fw_update_converted_t *conversion,
    uint16_t board_index
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->board_index = board_index; 
}


void bms_fw_update_conversion_to_raw(
    bms_fw_update_t *raw,
    uint16_t board_index
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
){
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = _timestamp;
#endif // CANLIB_TIMESTAMP
    raw->board_index = board_index; 
}


void bms_fw_update_raw_to_conversion_struct(
    bms_fw_update_converted_t *conversion, 
    const bms_fw_update_t *raw)
{
#ifdef CANLIB_TIMESTAMP
    conversion->_timestamp = raw->_timestamp;
#endif // CANLIB_TIMESTAMP
    conversion->board_index = raw->board_index; 
}


void bms_fw_update_conversion_to_raw_struct(
    bms_fw_update_t *raw,
    const bms_fw_update_converted_t *conversion)
{
#ifdef CANLIB_TIMESTAMP
    raw->_timestamp = conversion->_timestamp;
#endif // CANLIB_TIMESTAMP
    raw->board_index = conversion->board_index; 
}

int bms_fw_update_to_string(bms_fw_update_t *message, char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu16 "",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->board_index
);
}

int bms_fw_update_to_string_file(bms_fw_update_t *message, FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
        "%u"","
        #endif // CANLIB_TIMESTAMP
    "%" PRIu16 "",

#ifdef CANLIB_TIMESTAMP
    message->_timestamp,
#endif // CANLIB_TIMESTAMP
    message->board_index
);
}

int bms_fw_update_fields(char *buffer){
    return sprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "board_index");
}

int bms_fw_update_fields_file(FILE *buffer){
    return fprintf(
        buffer,
        ""
        #ifdef CANLIB_TIMESTAMP
            "_timestamp" ","
        #endif // CANLIB_TIMESTAMP
    "board_index");
}


int bms_flash_cellboard_0_tx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_0_tx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_0_tx_unpack(
    bms_flash_cellboard_0_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_0_tx_to_string(bms_flash_cellboard_0_tx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_0_tx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_0_tx_to_string_file(bms_flash_cellboard_0_tx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_0_tx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_0_rx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_0_rx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_0_rx_unpack(
    bms_flash_cellboard_0_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_0_rx_to_string(bms_flash_cellboard_0_rx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_0_rx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_0_rx_to_string_file(bms_flash_cellboard_0_rx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_0_rx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_1_tx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_1_tx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_1_tx_unpack(
    bms_flash_cellboard_1_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_1_tx_to_string(bms_flash_cellboard_1_tx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_1_tx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_1_tx_to_string_file(bms_flash_cellboard_1_tx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_1_tx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_1_rx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_1_rx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_1_rx_unpack(
    bms_flash_cellboard_1_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_1_rx_to_string(bms_flash_cellboard_1_rx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_1_rx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_1_rx_to_string_file(bms_flash_cellboard_1_rx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_1_rx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_2_tx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_2_tx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_2_tx_unpack(
    bms_flash_cellboard_2_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_2_tx_to_string(bms_flash_cellboard_2_tx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_2_tx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_2_tx_to_string_file(bms_flash_cellboard_2_tx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_2_tx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_2_rx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_2_rx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_2_rx_unpack(
    bms_flash_cellboard_2_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_2_rx_to_string(bms_flash_cellboard_2_rx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_2_rx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_2_rx_to_string_file(bms_flash_cellboard_2_rx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_2_rx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_3_tx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_3_tx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_3_tx_unpack(
    bms_flash_cellboard_3_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_3_tx_to_string(bms_flash_cellboard_3_tx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_3_tx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_3_tx_to_string_file(bms_flash_cellboard_3_tx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_3_tx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_3_rx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_3_rx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_3_rx_unpack(
    bms_flash_cellboard_3_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_3_rx_to_string(bms_flash_cellboard_3_rx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_3_rx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_3_rx_to_string_file(bms_flash_cellboard_3_rx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_3_rx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_4_tx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_4_tx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_4_tx_unpack(
    bms_flash_cellboard_4_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_4_tx_to_string(bms_flash_cellboard_4_tx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_4_tx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_4_tx_to_string_file(bms_flash_cellboard_4_tx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_4_tx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_4_rx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_4_rx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_4_rx_unpack(
    bms_flash_cellboard_4_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_4_rx_to_string(bms_flash_cellboard_4_rx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_4_rx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_4_rx_to_string_file(bms_flash_cellboard_4_rx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_4_rx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_5_tx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_5_tx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_5_tx_unpack(
    bms_flash_cellboard_5_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_5_tx_to_string(bms_flash_cellboard_5_tx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_5_tx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_5_tx_to_string_file(bms_flash_cellboard_5_tx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_5_tx_fields_file(FILE *buffer){return 0;}


int bms_flash_cellboard_5_rx_pack(
    uint8_t *dst_p,
    const bms_flash_cellboard_5_rx_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_5_rx_unpack(
    bms_flash_cellboard_5_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size
    #ifdef CANLIB_TIMESTAMP
        , uint64_t _timestamp
    #endif // CANLIB_TIMESTAM
)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int bms_flash_cellboard_5_rx_to_string(bms_flash_cellboard_5_rx_t *message, char *buffer){return 0;}
int bms_flash_cellboard_5_rx_fields(char *buffer) {return 0;}
int bms_flash_cellboard_5_rx_to_string_file(bms_flash_cellboard_5_rx_t *message, FILE *buffer){return 0;}
int bms_flash_cellboard_5_rx_fields_file(FILE *buffer){return 0;}


int bms_message_name_from_id(uint16_t id, char* buffer) {
    switch (id) {
		case 1698: return sprintf(buffer, "%s", "board_status");
		case 1443: return sprintf(buffer, "%s", "temperatures");
		case 672: return sprintf(buffer, "%s", "voltages");
		case 513: return sprintf(buffer, "%s", "balancing");
		case 10: return sprintf(buffer, "%s", "fw_update");
		case 16: return sprintf(buffer, "%s", "flash_cellboard_0_tx");
		case 17: return sprintf(buffer, "%s", "flash_cellboard_0_rx");
		case 18: return sprintf(buffer, "%s", "flash_cellboard_1_tx");
		case 19: return sprintf(buffer, "%s", "flash_cellboard_1_rx");
		case 20: return sprintf(buffer, "%s", "flash_cellboard_2_tx");
		case 21: return sprintf(buffer, "%s", "flash_cellboard_2_rx");
		case 22: return sprintf(buffer, "%s", "flash_cellboard_3_tx");
		case 23: return sprintf(buffer, "%s", "flash_cellboard_3_rx");
		case 24: return sprintf(buffer, "%s", "flash_cellboard_4_tx");
		case 25: return sprintf(buffer, "%s", "flash_cellboard_4_rx");
		case 26: return sprintf(buffer, "%s", "flash_cellboard_5_tx");
		case 27: return sprintf(buffer, "%s", "flash_cellboard_5_rx");
    }
    return 0;
}

int bms_index_from_id(uint16_t id) {
    switch (id) {
		case 1698: return bms_board_status_INDEX;
		case 1443: return bms_temperatures_INDEX;
		case 672: return bms_voltages_INDEX;
		case 513: return bms_balancing_INDEX;
		case 10: return bms_fw_update_INDEX;
		case 16: return bms_flash_cellboard_0_tx_INDEX;
		case 17: return bms_flash_cellboard_0_rx_INDEX;
		case 18: return bms_flash_cellboard_1_tx_INDEX;
		case 19: return bms_flash_cellboard_1_rx_INDEX;
		case 20: return bms_flash_cellboard_2_tx_INDEX;
		case 21: return bms_flash_cellboard_2_rx_INDEX;
		case 22: return bms_flash_cellboard_3_tx_INDEX;
		case 23: return bms_flash_cellboard_3_rx_INDEX;
		case 24: return bms_flash_cellboard_4_tx_INDEX;
		case 25: return bms_flash_cellboard_4_rx_INDEX;
		case 26: return bms_flash_cellboard_5_tx_INDEX;
		case 27: return bms_flash_cellboard_5_rx_INDEX;
    }
    return -1;
}

int bms_id_from_index(int index){
    switch (index) {
		case bms_board_status_INDEX: return 1698;
		case bms_temperatures_INDEX: return 1443;
		case bms_voltages_INDEX: return 672;
		case bms_balancing_INDEX: return 513;
		case bms_fw_update_INDEX: return 10;
		case bms_flash_cellboard_0_tx_INDEX: return 16;
		case bms_flash_cellboard_0_rx_INDEX: return 17;
		case bms_flash_cellboard_1_tx_INDEX: return 18;
		case bms_flash_cellboard_1_rx_INDEX: return 19;
		case bms_flash_cellboard_2_tx_INDEX: return 20;
		case bms_flash_cellboard_2_rx_INDEX: return 21;
		case bms_flash_cellboard_3_tx_INDEX: return 22;
		case bms_flash_cellboard_3_rx_INDEX: return 23;
		case bms_flash_cellboard_4_tx_INDEX: return 24;
		case bms_flash_cellboard_4_rx_INDEX: return 25;
		case bms_flash_cellboard_5_tx_INDEX: return 26;
		case bms_flash_cellboard_5_rx_INDEX: return 27;
    }
    return -1;
}

int bms_to_string_from_id(uint16_t message_id,
                                void* message,
                                char* buffer
) {
    switch (message_id) {
        case 1698:
            return bms_board_status_to_string((bms_board_status_t*) message,
                                                buffer);
        case 1443:
            return bms_temperatures_converted_to_string((bms_temperatures_converted_t*) message,
                                                buffer);
        case 672:
            return bms_voltages_converted_to_string((bms_voltages_converted_t*) message,
                                                buffer);
        case 513:
            return bms_balancing_to_string((bms_balancing_t*) message,
                                                buffer);
        case 10:
            return bms_fw_update_to_string((bms_fw_update_t*) message,
                                                buffer);
        case 16:
            return bms_flash_cellboard_0_tx_to_string((bms_flash_cellboard_0_tx_t*) message,
                                                buffer);
        case 17:
            return bms_flash_cellboard_0_rx_to_string((bms_flash_cellboard_0_rx_t*) message,
                                                buffer);
        case 18:
            return bms_flash_cellboard_1_tx_to_string((bms_flash_cellboard_1_tx_t*) message,
                                                buffer);
        case 19:
            return bms_flash_cellboard_1_rx_to_string((bms_flash_cellboard_1_rx_t*) message,
                                                buffer);
        case 20:
            return bms_flash_cellboard_2_tx_to_string((bms_flash_cellboard_2_tx_t*) message,
                                                buffer);
        case 21:
            return bms_flash_cellboard_2_rx_to_string((bms_flash_cellboard_2_rx_t*) message,
                                                buffer);
        case 22:
            return bms_flash_cellboard_3_tx_to_string((bms_flash_cellboard_3_tx_t*) message,
                                                buffer);
        case 23:
            return bms_flash_cellboard_3_rx_to_string((bms_flash_cellboard_3_rx_t*) message,
                                                buffer);
        case 24:
            return bms_flash_cellboard_4_tx_to_string((bms_flash_cellboard_4_tx_t*) message,
                                                buffer);
        case 25:
            return bms_flash_cellboard_4_rx_to_string((bms_flash_cellboard_4_rx_t*) message,
                                                buffer);
        case 26:
            return bms_flash_cellboard_5_tx_to_string((bms_flash_cellboard_5_tx_t*) message,
                                                buffer);
        case 27:
            return bms_flash_cellboard_5_rx_to_string((bms_flash_cellboard_5_rx_t*) message,
                                                buffer);
    }
	return 0;
}

int bms_fields_from_id(uint16_t message_id, char* buffer) {
    switch (message_id) {
        case 1698:
            return bms_board_status_fields(buffer);
        case 1443:
            return bms_temperatures_fields(buffer);
        case 672:
            return bms_voltages_fields(buffer);
        case 513:
            return bms_balancing_fields(buffer);
        case 10:
            return bms_fw_update_fields(buffer);
        case 16:
            return bms_flash_cellboard_0_tx_fields(buffer);
        case 17:
            return bms_flash_cellboard_0_rx_fields(buffer);
        case 18:
            return bms_flash_cellboard_1_tx_fields(buffer);
        case 19:
            return bms_flash_cellboard_1_rx_fields(buffer);
        case 20:
            return bms_flash_cellboard_2_tx_fields(buffer);
        case 21:
            return bms_flash_cellboard_2_rx_fields(buffer);
        case 22:
            return bms_flash_cellboard_3_tx_fields(buffer);
        case 23:
            return bms_flash_cellboard_3_rx_fields(buffer);
        case 24:
            return bms_flash_cellboard_4_tx_fields(buffer);
        case 25:
            return bms_flash_cellboard_4_rx_fields(buffer);
        case 26:
            return bms_flash_cellboard_5_tx_fields(buffer);
        case 27:
            return bms_flash_cellboard_5_rx_fields(buffer);
    }
	return 0;
}

int bms_to_string_file_from_id(uint16_t message_id, void* message, FILE* buffer) {
    switch (message_id) {
        case 1698:
            return bms_board_status_to_string_file((bms_board_status_t*) message, buffer);
        case 1443:
            return bms_temperatures_converted_to_string_file((bms_temperatures_converted_t*) message, buffer);
        case 672:
            return bms_voltages_converted_to_string_file((bms_voltages_converted_t*) message, buffer);
        case 513:
            return bms_balancing_to_string_file((bms_balancing_t*) message, buffer);
        case 10:
            return bms_fw_update_to_string_file((bms_fw_update_t*) message, buffer);
        case 16:
            return bms_flash_cellboard_0_tx_to_string_file((bms_flash_cellboard_0_tx_t*) message, buffer);
        case 17:
            return bms_flash_cellboard_0_rx_to_string_file((bms_flash_cellboard_0_rx_t*) message, buffer);
        case 18:
            return bms_flash_cellboard_1_tx_to_string_file((bms_flash_cellboard_1_tx_t*) message, buffer);
        case 19:
            return bms_flash_cellboard_1_rx_to_string_file((bms_flash_cellboard_1_rx_t*) message, buffer);
        case 20:
            return bms_flash_cellboard_2_tx_to_string_file((bms_flash_cellboard_2_tx_t*) message, buffer);
        case 21:
            return bms_flash_cellboard_2_rx_to_string_file((bms_flash_cellboard_2_rx_t*) message, buffer);
        case 22:
            return bms_flash_cellboard_3_tx_to_string_file((bms_flash_cellboard_3_tx_t*) message, buffer);
        case 23:
            return bms_flash_cellboard_3_rx_to_string_file((bms_flash_cellboard_3_rx_t*) message, buffer);
        case 24:
            return bms_flash_cellboard_4_tx_to_string_file((bms_flash_cellboard_4_tx_t*) message, buffer);
        case 25:
            return bms_flash_cellboard_4_rx_to_string_file((bms_flash_cellboard_4_rx_t*) message, buffer);
        case 26:
            return bms_flash_cellboard_5_tx_to_string_file((bms_flash_cellboard_5_tx_t*) message, buffer);
        case 27:
            return bms_flash_cellboard_5_rx_to_string_file((bms_flash_cellboard_5_rx_t*) message, buffer);
    }
	return 0;
}

int bms_fields_file_from_id(uint16_t message_id, FILE* buffer) {
    switch (message_id) {
        case 1698:
            return bms_board_status_fields_file(buffer);
        case 1443:
            return bms_temperatures_fields_file(buffer);
        case 672:
            return bms_voltages_fields_file(buffer);
        case 513:
            return bms_balancing_fields_file(buffer);
        case 10:
            return bms_fw_update_fields_file(buffer);
        case 16:
            return bms_flash_cellboard_0_tx_fields_file(buffer);
        case 17:
            return bms_flash_cellboard_0_rx_fields_file(buffer);
        case 18:
            return bms_flash_cellboard_1_tx_fields_file(buffer);
        case 19:
            return bms_flash_cellboard_1_rx_fields_file(buffer);
        case 20:
            return bms_flash_cellboard_2_tx_fields_file(buffer);
        case 21:
            return bms_flash_cellboard_2_rx_fields_file(buffer);
        case 22:
            return bms_flash_cellboard_3_tx_fields_file(buffer);
        case 23:
            return bms_flash_cellboard_3_rx_fields_file(buffer);
        case 24:
            return bms_flash_cellboard_4_tx_fields_file(buffer);
        case 25:
            return bms_flash_cellboard_4_rx_fields_file(buffer);
        case 26:
            return bms_flash_cellboard_5_tx_fields_file(buffer);
        case 27:
            return bms_flash_cellboard_5_rx_fields_file(buffer);
    }
	return 0;
}

bms_devices* bms_devices_new() {
    bms_devices* devices = (bms_devices*) malloc(sizeof(bms_devices));
    (*devices)[bms_board_status_INDEX].id = 1698;
    (*devices)[bms_board_status_INDEX].message_raw = (void*) malloc(sizeof(bms_board_status_t));
    (*devices)[bms_board_status_INDEX].message_conversion = NULL;
    (*devices)[bms_temperatures_INDEX].id = 1443;
    (*devices)[bms_temperatures_INDEX].message_raw = (void*) malloc(sizeof(bms_temperatures_t));
    (*devices)[bms_temperatures_INDEX].message_conversion = (void*) malloc(sizeof(bms_temperatures_converted_t));
    (*devices)[bms_voltages_INDEX].id = 672;
    (*devices)[bms_voltages_INDEX].message_raw = (void*) malloc(sizeof(bms_voltages_t));
    (*devices)[bms_voltages_INDEX].message_conversion = (void*) malloc(sizeof(bms_voltages_converted_t));
    (*devices)[bms_balancing_INDEX].id = 513;
    (*devices)[bms_balancing_INDEX].message_raw = (void*) malloc(sizeof(bms_balancing_t));
    (*devices)[bms_balancing_INDEX].message_conversion = NULL;
    (*devices)[bms_fw_update_INDEX].id = 10;
    (*devices)[bms_fw_update_INDEX].message_raw = (void*) malloc(sizeof(bms_fw_update_t));
    (*devices)[bms_fw_update_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_0_tx_INDEX].id = 16;
    (*devices)[bms_flash_cellboard_0_tx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_0_tx_t));
    (*devices)[bms_flash_cellboard_0_tx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_0_rx_INDEX].id = 17;
    (*devices)[bms_flash_cellboard_0_rx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_0_rx_t));
    (*devices)[bms_flash_cellboard_0_rx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_1_tx_INDEX].id = 18;
    (*devices)[bms_flash_cellboard_1_tx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_1_tx_t));
    (*devices)[bms_flash_cellboard_1_tx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_1_rx_INDEX].id = 19;
    (*devices)[bms_flash_cellboard_1_rx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_1_rx_t));
    (*devices)[bms_flash_cellboard_1_rx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_2_tx_INDEX].id = 20;
    (*devices)[bms_flash_cellboard_2_tx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_2_tx_t));
    (*devices)[bms_flash_cellboard_2_tx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_2_rx_INDEX].id = 21;
    (*devices)[bms_flash_cellboard_2_rx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_2_rx_t));
    (*devices)[bms_flash_cellboard_2_rx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_3_tx_INDEX].id = 22;
    (*devices)[bms_flash_cellboard_3_tx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_3_tx_t));
    (*devices)[bms_flash_cellboard_3_tx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_3_rx_INDEX].id = 23;
    (*devices)[bms_flash_cellboard_3_rx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_3_rx_t));
    (*devices)[bms_flash_cellboard_3_rx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_4_tx_INDEX].id = 24;
    (*devices)[bms_flash_cellboard_4_tx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_4_tx_t));
    (*devices)[bms_flash_cellboard_4_tx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_4_rx_INDEX].id = 25;
    (*devices)[bms_flash_cellboard_4_rx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_4_rx_t));
    (*devices)[bms_flash_cellboard_4_rx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_5_tx_INDEX].id = 26;
    (*devices)[bms_flash_cellboard_5_tx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_5_tx_t));
    (*devices)[bms_flash_cellboard_5_tx_INDEX].message_conversion = NULL;
    (*devices)[bms_flash_cellboard_5_rx_INDEX].id = 27;
    (*devices)[bms_flash_cellboard_5_rx_INDEX].message_raw = (void*) malloc(sizeof(bms_flash_cellboard_5_rx_t));
    (*devices)[bms_flash_cellboard_5_rx_INDEX].message_conversion = NULL;
    return devices;
}

void bms_devices_free(bms_devices* devices) {
    free((*devices)[bms_board_status_INDEX].message_raw);
    free((*devices)[bms_temperatures_INDEX].message_raw);
    free((*devices)[bms_voltages_INDEX].message_raw);
    free((*devices)[bms_balancing_INDEX].message_raw);
    free((*devices)[bms_fw_update_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_0_tx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_0_rx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_1_tx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_1_rx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_2_tx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_2_rx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_3_tx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_3_rx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_4_tx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_4_rx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_5_tx_INDEX].message_raw);
    free((*devices)[bms_flash_cellboard_5_rx_INDEX].message_raw);
    free(devices);
}

void bms_devices_deserialize_from_id(
    bms_devices* devices,
    uint16_t message_id,
    uint8_t* data
    #ifdef CANLIB_TIMESTAMP
    , uint64_t timestamp
    #endif // CANLIB_TIMESTAMP
)
{
    switch(message_id){
        case 1698: {
            bms_board_status_unpack(
                (bms_board_status_t*) (*devices)[bms_board_status_INDEX].message_raw,
                data,
                17
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 1443: {
            bms_temperatures_unpack(
                (bms_temperatures_t*) (*devices)[bms_temperatures_INDEX].message_raw,
                data,
                112
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            bms_temperatures_raw_to_conversion_struct(
                (*devices)[bms_temperatures_INDEX].message_conversion,
                (*devices)[bms_temperatures_INDEX].message_raw
            );

            return;
        }
        case 672: {
            bms_voltages_unpack(
                (bms_voltages_t*) (*devices)[bms_voltages_INDEX].message_raw,
                data,
                40
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            bms_voltages_raw_to_conversion_struct(
                (*devices)[bms_voltages_INDEX].message_conversion,
                (*devices)[bms_voltages_INDEX].message_raw
            );

            return;
        }
        case 513: {
            bms_balancing_unpack(
                (bms_balancing_t*) (*devices)[bms_balancing_INDEX].message_raw,
                data,
                34
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 10: {
            bms_fw_update_unpack(
                (bms_fw_update_t*) (*devices)[bms_fw_update_INDEX].message_raw,
                data,
                16
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 16: {
            bms_flash_cellboard_0_tx_unpack(
                (bms_flash_cellboard_0_tx_t*) (*devices)[bms_flash_cellboard_0_tx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 17: {
            bms_flash_cellboard_0_rx_unpack(
                (bms_flash_cellboard_0_rx_t*) (*devices)[bms_flash_cellboard_0_rx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 18: {
            bms_flash_cellboard_1_tx_unpack(
                (bms_flash_cellboard_1_tx_t*) (*devices)[bms_flash_cellboard_1_tx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 19: {
            bms_flash_cellboard_1_rx_unpack(
                (bms_flash_cellboard_1_rx_t*) (*devices)[bms_flash_cellboard_1_rx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 20: {
            bms_flash_cellboard_2_tx_unpack(
                (bms_flash_cellboard_2_tx_t*) (*devices)[bms_flash_cellboard_2_tx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 21: {
            bms_flash_cellboard_2_rx_unpack(
                (bms_flash_cellboard_2_rx_t*) (*devices)[bms_flash_cellboard_2_rx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 22: {
            bms_flash_cellboard_3_tx_unpack(
                (bms_flash_cellboard_3_tx_t*) (*devices)[bms_flash_cellboard_3_tx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 23: {
            bms_flash_cellboard_3_rx_unpack(
                (bms_flash_cellboard_3_rx_t*) (*devices)[bms_flash_cellboard_3_rx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 24: {
            bms_flash_cellboard_4_tx_unpack(
                (bms_flash_cellboard_4_tx_t*) (*devices)[bms_flash_cellboard_4_tx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 25: {
            bms_flash_cellboard_4_rx_unpack(
                (bms_flash_cellboard_4_rx_t*) (*devices)[bms_flash_cellboard_4_rx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 26: {
            bms_flash_cellboard_5_tx_unpack(
                (bms_flash_cellboard_5_tx_t*) (*devices)[bms_flash_cellboard_5_tx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }
        case 27: {
            bms_flash_cellboard_5_rx_unpack(
                (bms_flash_cellboard_5_rx_t*) (*devices)[bms_flash_cellboard_5_rx_INDEX].message_raw,
                data,
                0
                #ifdef CANLIB_TIMESTAMP
                , timestamp
                #endif
            );
            
            return;
        }

    }
}
